# Creation of counts of HCPs, hospitals and calls

In this notebook, we calculate the following things for each BC and melanoma region:

* how many HCPs there are 
* how many hospitals there are
* how many promotional calls were made there in each month from 01-2020 to 08-2021

First, we prepare targets and calls in such a way that the HCP and hospital counts can be determined from them. Subsequently, we calculate the call counts and then the HCP counts and hospital counts.

In [1]:
import pandas as pd
import os

#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

## Define helper functions

In [2]:
def aggregate_by_regions_and_dates(mapping, data, variable, new_column):
    """
    Aggregate the data by regions to obtain the counts for hospitals or HCPs.
    """
    counts = mapping.copy()

    data_no_duplicates = data[~data.duplicated(subset=['date', variable, 'indication'])]
    
    for date in data['date'].unique():
        
        #counts_total = pd.DataFrame()

        for i in range(len(counts['brick'])):
            brick = counts['brick'][i]
            counts.at[i, 'count_bc'] = len(data_no_duplicates[(data_no_duplicates['date'] == date) & (data_no_duplicates['municipality'] == brick) & (data_no_duplicates['indication'] == 'BC')])
            counts.at[i, 'count_me'] = len(data_no_duplicates[(data_no_duplicates['date'] == date) & (data_no_duplicates['municipality'] == brick) & (data_no_duplicates['indication'] == 'Melanoma')])
    
    # Group and sum by 'count_bc'
    counts_bc = counts.filter(items=['date', 'brick', 'sweden_bc', 'count_bc'])
    counts_bc = counts_bc.rename(columns = {'count_bc': new_column})
    counts_bc['sweden_bc'] = counts_bc['sweden_bc'].cat.remove_unused_categories(inplace = False)
    counts_bc = counts_bc.groupby(by = ['date', 'sweden_bc']).sum().reset_index()

    # Rename 'sweden_bc' to 'territory'
    counts_bc = counts_bc.rename(columns = {"sweden_bc": "territory"})

    # Group and sum by 'count_me'
    counts_me = counts.filter(items=['date', 'brick', 'sweden_me', 'count_me'])
    counts_me = counts_me.rename(columns = {'count_me': new_column})
    counts_me['sweden_me'] = counts_me['sweden_me'].cat.remove_unused_categories(inplace = False)
    counts_me = counts_me.groupby(by = ['date', 'sweden_me']).sum().reset_index()

    # Rename 'sweden_me' to 'territory'
    counts_me = counts_me.rename(columns = {"sweden_me": "territory"})

    # Concatenate counts_bc and counts_me
    counts = pd.concat([counts_bc, counts_me], ignore_index = True)

    return(counts)

In [3]:
def aggregate_by_regions(mapping, data, variable, new_column):
    """
    Aggregate the data by regions to obtain the counts for hospitals or HCPs.
    """
    counts = mapping.copy()

    data_no_duplicates = data[~data.duplicated(subset=[variable, 'indication'])]

    for i in range(len(counts['brick'])):
        brick = counts['brick'][i]
        counts.at[i, 'count_bc'] = len(data_no_duplicates[(data_no_duplicates['municipality'] == brick) & (data_no_duplicates['indication'] == 'BC')])
        counts.at[i, 'count_me'] = len(data_no_duplicates[(data_no_duplicates['municipality'] == brick) & (data_no_duplicates['indication'] == 'Melanoma')])
    
    # Group and sum by 'count_bc'
    counts_bc = counts.filter(items=['brick', 'sweden_bc', 'count_bc'])
    counts_bc = counts_bc.rename(columns = {'count_bc': new_column})
    counts_bc = counts_bc.groupby(by = 'sweden_bc').sum().reset_index()

    # Rename 'sweden_bc' to 'territory'
    counts_bc = counts_bc.rename(columns = {"sweden_bc": "territory"})

    # Group and sum by 'count_me'
    counts_me = counts.filter(items=['brick', 'sweden_me', 'count_me'])
    counts_me = counts_me.rename(columns = {'count_me': new_column})
    counts_me = counts_me.groupby(by = 'sweden_me').sum().reset_index()

    # Rename 'sweden_me' to 'territory'
    counts_me = counts_me.rename(columns = {"sweden_me": "territory"})

    # Concatenate counts_bc and counts_me
    counts = pd.concat([counts_bc, counts_me], ignore_index = True)
    
    return(counts)

## Load data

In [4]:
# Read in datasets
route0 = "../processed_data"

targets = pd.read_pickle(f"{route0}/targets.pkl")
calls = pd.read_pickle(f"{route0}/calls.pkl")
svenska_stader = pd.read_pickle(f"{route0}/svenska_stader.pkl")
mapping = pd.read_pickle(f"{route0}/mapping.pkl")

## 1. Targets: Preparation for HCP and hospital counts

In this part, we prepare the targets to be later used for the HCP and hospital counts.

In [5]:
targets = targets.drop(columns=[ 'address', 'locality', 'municipality', 'territory'])
targets

account_name account_record_type account_type  \
0        Adel Bader Hamdalla                 HCP       Doctor   
1              Aglaia Schiza                 HCP       Doctor   
2      Agneta Nordin Danfors                 HCP       Doctor   
3    Ahmed Abbas Albu-Kareem                 HCP       Doctor   
4                Alaa Haidar                 HCP       Doctor   
..                       ...                 ...          ...   
224   Ylva Holmgren Stenlund                 HCP       Doctor   
225              Anna Nyberg                 HCP       Doctor   
226          Göran Carlstedt                 HCP       Doctor   
227         Mikael Wallander                 HCP       Doctor   
228          Frida Jakobsson                 HCP       Doctor   

       primary_specialty          primary_parent_name  \
0         SE-42-Onkologi  Avd E71 Hematologi onkologi   
1         SE-42-Onkologi              Onkologkliniken   
2    SE-1J-Bröstonkologi        Drottningmottagningen   
3         SE-42-Onkologi         Onkologiska kliniken   
4         SE-42-Onkologi          Onkologiska enheten   
..                   ...                          ...   
224       SE-42-Onkologi                Cancercentrum   
225       SE-42-Onkologi              Onkologkliniken   
226       SE-42-Onkologi              Onkologkliniken   
227       SE-42-Onkologi              Onkologkliniken   
228       SE-42-Onkologi         Onkologiska kliniken   

                    top_account_name indication tier segment       account_id  
0      Södra Älvsborgs Sjukhus Borås         BC   T3      S3  0012o00002kTDKp  
1               Akademiska sjukhuset         BC   T3      S3  0012o00002kTBeA  
2              Drottningmottagningen         BC   T2      S2  0012o00002iEZxE  
3    Universitetssjukhuset Linköping         BC   T2      S2  0012o00002kTAKC  
4          Hallands sjukhus Halmstad         BC   T2      S2  0012o00002iDs1j  
..                               ...        ...  ...     ...              ...  
224    Norrlands Universitetssjukhus   Melanoma   T2      S3  0012o00002iEaBJ  
225              Länssjukhuset Ryhov         BC   T3      S3  0012o00002iEYHR  
226          Centrallasarettet Växjö   Melanoma   T2      S3  0012o00002iETYR  
227              Länssjukhuset Ryhov   Melanoma   T2      S3  0012o00002kT9l2  
228     Universitetssjukhuset Örebro   Melanoma   T1      S3  0012o00002iETXT  

[229 rows x 10 columns]

In order to be able to assign a hospital to a BC or Melanoma region later, we need to find out what city a hospital given in `top_account_name` is located in. 
So, we now create a dictionary that maps each hospital given in the above list to its respective address. The addresses have been looked up by hand on Google Maps (21/02/22, 12:00-13:00).

In [6]:
# These addresses were looked up by hand on Google Maps - 21.02.2022, 12:00-13:00 
address_dict = {'Södra Älvsborgs Sjukhus Borås': 'Brämhultsvägen 53, 501 82 Borås, Schweden',
                'Akademiska sjukhuset': 'Sjukhusvägen, 751 85 Uppsala, Schweden',
                'Drottningmottagningen': 'Drottninggatan 68, 111 21 Stockholm, Schweden',
                'Universitetssjukhuset Linköping': 'Universitetssjukhuset, 581 85 Linköping, Schweden',
                'Hallands sjukhus Halmstad': 'Lasarettsvägen, 302 33 Halmstad, Schweden',
                'Lunds Universitet': 'Lund, Schweden',
                'Mälarsjukhuset': 'Kungsvägen 42, 633 49 Eskilstuna, Schweden',
                'Skellefteå Lasarett': 'Lasarettsvägen 29, 931 41 Skellefteå, Schweden',
                'Universitetssjukhuset Örebro': 'Södra Grev Rosengatan, 701 85 Örebro, Schweden',
                'Capio S:t Görans Sjukhus AB': 'Sankt Göransplan 1, 112 19 Stockholm, Schweden',
                'Blekingesjukhuset i Karlskrona': 'Lasarettsvägen, 371 41 Karlskrona, Schweden',
                'Södersjukhuset': 'Sjukhusbacken 10, 118 83 Stockholm, Schweden',
                'Uddevalla sjukhus': 'Fjällvägen 9, 451 53 Uddevalla, Schweden',
                'Länssjh Sundsvall-Härnösand': 'Lasarettsvägen 21, 856 43 Sundsvall, Schweden',
                'Sophiahemmet AB': 'Valhallavägen 91, 114 86 Stockholm, Schweden',
                'Norrlands Universitetssjukhus': 'Daniel Naezéns väg, 907 37 Umeå, Schweden',
                'Sahlgrenska Univ sjh': 'Blå stråket 5, 413 45 Göteborg, Schweden',
                'Skånes Universitetssjukhus Malmö': 'Carl-Bertil Laurells gata 9, 214 28 Malmö, Schweden',
                'Västmanlands sjukhus Västerås': 'Sigtunagatan, 721 89 Västerås, Schweden',
                'Länssjukhuset i Kalmar': 'Lasarettsvägen 8, 392 44 Kalmar, Schweden',
                'Skånes Universitetssjukhus Lund': 'Entrégatan 7, 222 42 Lund, Schweden',
                'Karolinska Univ Sjh Solna': 'Eugeniavägen 3, 171 64 Solna, Schweden',
                'Visby lasarett': 'S:t Göransgatan 5, 621 55 Visby, Schweden',
                'Länssjukhuset Ryhov': 'Sjukhusgatan, 553 05 Jönköping, Schweden',
                'Gävle Sjukhus': 'Lasarettsvägen 5, 803 24 Gävle, Schweden',
                'Centralsjukhuset i Karlstad': 'Rosenborgsgatan 9, 652 30 Karlstad, Schweden',
                'Centrallasarettet Växjö': 'Strandvägen 8, 352 34 Växjö, Schweden',
                'Falu Lasarett': 'Lasarettsvägen 10, 791 82 Falun, Schweden',
                'Skaraborgs Sjh Lidköping': 'Mellbygatan 11, 531 51 Lidköping, Schweden',
                'Helsingborgs lasarett': 'Charlotte Yhlens gata 10, 252 23 Helsingborg, Schweden',
                'Östersunds Sjukhus': 'Kyrkgatan 16, 831 31 Östersund, Schweden',
                'Skaraborgs Sjukhus Skövde': 'Lövängsvägen, 541 42 Skövde, Schweden',
                'Hallands sjukhus Varberg': 'Träslövsvägen 68, 432 37 Varberg, Schweden'}

The relevant columns to get the number of hospitals and HCPs in the BC and Melanoma regions are `account_name`, `top_account_name`, `indication`. We therefore select these columns now. 

In [7]:
targets_subset = targets.filter(items=['account_name', 'top_account_name', 'indication'])
targets_subset

account_name                 top_account_name indication
0        Adel Bader Hamdalla    Södra Älvsborgs Sjukhus Borås         BC
1              Aglaia Schiza             Akademiska sjukhuset         BC
2      Agneta Nordin Danfors            Drottningmottagningen         BC
3    Ahmed Abbas Albu-Kareem  Universitetssjukhuset Linköping         BC
4                Alaa Haidar        Hallands sjukhus Halmstad         BC
..                       ...                              ...        ...
224   Ylva Holmgren Stenlund    Norrlands Universitetssjukhus   Melanoma
225              Anna Nyberg              Länssjukhuset Ryhov         BC
226          Göran Carlstedt          Centrallasarettet Växjö   Melanoma
227         Mikael Wallander              Länssjukhuset Ryhov   Melanoma
228          Frida Jakobsson     Universitetssjukhuset Örebro   Melanoma

[229 rows x 3 columns]

We now add a new column `address` with the addresses from `address_dict`.

In [8]:
targets_subset["address"] = targets_subset["top_account_name"].apply(lambda x: address_dict.get(x))
targets_subset

account_name                 top_account_name indication  \
0        Adel Bader Hamdalla    Södra Älvsborgs Sjukhus Borås         BC   
1              Aglaia Schiza             Akademiska sjukhuset         BC   
2      Agneta Nordin Danfors            Drottningmottagningen         BC   
3    Ahmed Abbas Albu-Kareem  Universitetssjukhuset Linköping         BC   
4                Alaa Haidar        Hallands sjukhus Halmstad         BC   
..                       ...                              ...        ...   
224   Ylva Holmgren Stenlund    Norrlands Universitetssjukhus   Melanoma   
225              Anna Nyberg              Länssjukhuset Ryhov         BC   
226          Göran Carlstedt          Centrallasarettet Växjö   Melanoma   
227         Mikael Wallander              Länssjukhuset Ryhov   Melanoma   
228          Frida Jakobsson     Universitetssjukhuset Örebro   Melanoma   

                                               address  
0            Brämhultsvägen 53, 501 82 Borås, Schweden  
1               Sjukhusvägen, 751 85 Uppsala, Schweden  
2        Drottninggatan 68, 111 21 Stockholm, Schweden  
3    Universitetssjukhuset, 581 85 Linköping, Schweden  
4            Lasarettsvägen, 302 33 Halmstad, Schweden  
..                                                 ...  
224          Daniel Naezéns väg, 907 37 Umeå, Schweden  
225           Sjukhusgatan, 553 05 Jönköping, Schweden  
226              Strandvägen 8, 352 34 Växjö, Schweden  
227           Sjukhusgatan, 553 05 Jönköping, Schweden  
228     Södra Grev Rosengatan, 701 85 Örebro, Schweden  

[229 rows x 4 columns]

The data frame `targets_subset` is now prepared to be used for the HCP and hospital counts.

## 2. Calls: Preparation for HCP and hospital counts

We now conduct some preparation steps with calls to be used for HCP and hospital counts later, not for the call counts.

The information from calls is meant to complement the information obtained from the targets table.
This means we suppose the hospitals stay the same, only HCPs are added.

In [9]:
hcp_list = targets['account_name'].unique().tolist()

# look only at HCPs we do not know yet from targets (and exclude HCOs)
calls_subset = calls.loc[(~calls['account_name'].isin(hcp_list)) & (calls['account_record_type'] == 'HCP')].reset_index(drop=True)

calls_subset

call_name account_record_type parent_call       date  \
0    C004360771                 HCP         0.0 2020-01-16   
1    C004360773                 HCP         0.0 2020-01-16   
2    C004360776                 HCP         0.0 2020-01-16   
3    C004360777                 HCP         0.0 2020-01-16   
4    C004360780                 HCP         0.0 2020-01-16   
..          ...                 ...         ...        ...   
174  C010427094                 HCP         0.0 2021-09-15   
175  C010427095                 HCP         0.0 2021-09-15   
176  C010427096                 HCP         0.0 2021-09-15   
177  C010427097                 HCP         0.0 2021-09-15   
178  C010427098                 HCP         0.0 2021-09-15   

               datetime       account_name  \
0   2020-01-16 21:17:00      David Sterner   
1   2020-01-16 21:17:00      Lars Sandberg   
2   2020-01-16 21:17:00     Cecilia Kamali   
3   2020-01-16 21:17:00      Åsa Jonforsen   
4   2020-01-16 21:17:00    David Goldstein   
..                  ...                ...   
174 2021-09-15 12:00:00   Pernilla Nilsson   
175 2021-09-15 12:00:00   Sandra Sjöstrand   
176 2021-09-15 12:00:00       Pia Törnblom   
177 2021-09-15 12:00:00  Karolina Vernmark   
178 2021-09-15 12:00:00      Maria Östlund   

                                               address       address_line_1  \
0    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
1    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
2    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
3    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
4    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
..                                                 ...                  ...   
174  Garnisonsvägen 10, LINKÖPING, Östergötlands lä...    Garnisonsvägen 10   
175  Garnisonsvägen 10, LINKÖPING, Östergötlands lä...    Garnisonsvägen 10   
176  Garnisonsvägen 10, LINKÖPING, Östergötlands lä...    Garnisonsvägen 10   
177  Garnisonsvägen 10, LINKÖPING, Östergötlands lä...    Garnisonsvägen 10   
178  Garnisonsvägen 10, LINKÖPING, Östergötlands lä...    Garnisonsvägen 10   

     attendees   attendee_type              call_focus       call_method  \
0          0.0  Person Account  Promotional discussion      Face to Face   
1          0.0  Person Account  Promotional discussion      Face to Face   
2          0.0  Person Account  Promotional discussion      Face to Face   
3          0.0  Person Account  Promotional discussion      Face to Face   
4          0.0  Person Account  Promotional discussion      Face to Face   
..         ...             ...                     ...               ...   
174        0.0  Person Account  Promotional discussion  Virtual MS Teams   
175        0.0  Person Account  Promotional discussion  Virtual MS Teams   
176        0.0  Person Account  Promotional discussion  Virtual MS Teams   
177        0.0  Person Account  Promotional discussion  Virtual MS Teams   
178        0.0  Person Account  Promotional discussion  Virtual MS Teams   

     duration_in_minutes       account_id indication  
0                   30.0  0012o00002kTsAl   Melanoma  
1                   30.0  0012o00002iEVS2   Melanoma  
2                   30.0  0012o00002iDoJT   Melanoma  
3                   30.0  0012o00002iEWSI   Melanoma  
4                   30.0  0012o00002kTlW5   Melanoma  
..                   ...              ...        ...  
174                 45.0  0012o00002kTp20   Melanoma  
175                 45.0  0012o00002iEdyx   Melanoma  
176                 45.0  0012o00002iDrMc   Melanoma  
177                 45.0  0012o00002iEQjh   Melanoma  
178                 45.0  0012o00002iEdj0   Melanoma  

[179 rows x 15 columns]

### I. Multiple Assignment

Looking at the data frame, we see that some HCPs have more than one address/hospital assigned to them. The HCPs are:

* Björn Sigurdsson
* Hanna Eriksson (Solna, Lund)
* Lars Larsson (Boras, Lund)
* Muhammad Kadum (Lund, Kristianstad)

Let us take a closer look at these cases.

#### Björn Sigurdsson

In [10]:
calls_subset[calls_subset['account_name'] == 'Björn Sigurdsson']

call_name account_record_type parent_call       date            datetime  \
35  C004371901                 HCP         0.0 2020-06-03 2020-06-03 11:01:00   
45  C005656684                 HCP         1.0 2020-08-25 2020-08-25 14:30:00   
65  C005889050                 HCP         1.0 2020-09-29 2020-09-29 14:00:00   
74  C009587636                 HCP         1.0 2020-10-19 2020-10-19 11:00:00   

        account_name                                            address  \
35  Björn Sigurdsson  Barn- och ungdomsmedicin, Jan Waldenströms gat...   
45  Björn Sigurdsson                        SE-Arbetsplats okänd Sweden   
65  Björn Sigurdsson                        SE-Arbetsplats okänd Sweden   
74  Björn Sigurdsson                                                nan   

              address_line_1  attendees   attendee_type call_focus  \
35  Jan Waldenströms gata 18        0.0  Person Account        NaN   
45      SE-Arbetsplats okänd        0.0  Person Account        NaN   
65      SE-Arbetsplats okänd        0.0  Person Account        NaN   
74                       nan        0.0  Person Account        NaN   

        call_method  duration_in_minutes       account_id indication  
35            Phone                 30.0  0012o00002iEYtq   Melanoma  
45              NaN                 30.0  0012o00002iEYtq   Melanoma  
65            Phone                 30.0  0012o00002iEYtq   Melanoma  
74  Voice-only Call                 20.0  0012o00002iEYtq   Melanoma

In [11]:
calls_subset['address'][35]

'Barn- och ungdomsmedicin, Jan Waldenströms gata 18, MALMÖ 21428'

Row 35 tells us that Björn Sigurdsson is from Malmö.

#### Hanna Eriksson

In [12]:
calls_subset[calls_subset['account_name'] == 'Hanna Eriksson']

call_name account_record_type parent_call       date  \
95   C009537214                 HCP         1.0 2021-04-06   
97   C009318413                 HCP         1.0 2021-04-20   
105  C009318244                 HCP         1.0 2021-05-05   
119  C009458860                 HCP         0.0 2021-05-25   
120  C009485879                 HCP         0.0 2021-05-27   
124  C009541730                 HCP         0.0 2021-05-27   
131  C009602973                 HCP         0.0 2021-06-02   
132  C009582426                 HCP         1.0 2021-06-04   
136  C009840057                 HCP         1.0 2021-06-16   
147  C009840065                 HCP         1.0 2021-06-21   
151  C010297220                 HCP         1.0 2021-08-30   
152  C010301595                 HCP         1.0 2021-09-02   

               datetime    account_name  \
95  2021-04-06 15:29:00  Hanna Eriksson   
97  2021-04-20 08:00:00  Hanna Eriksson   
105 2021-05-05 08:00:00  Hanna Eriksson   
119 2021-05-25 15:10:00  Hanna Eriksson   
120 2021-05-27 17:00:00  Hanna Eriksson   
124 2021-05-27 17:00:00  Hanna Eriksson   
131 2021-06-02 09:00:00  Hanna Eriksson   
132 2021-06-04 16:30:00  Hanna Eriksson   
136 2021-06-16 08:00:00  Hanna Eriksson   
147 2021-06-21 08:00:00  Hanna Eriksson   
151 2021-08-30 08:00:00  Hanna Eriksson   
152 2021-09-02 08:00:00  Hanna Eriksson   

                                               address    address_line_1  \
95   Eugeniavägen 3, SOLNA, Stockholms län A-B 1716...    Eugeniavägen 3   
97   Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
105  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
119  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
120         Entregatan 7, LUND, Skåne län 22241 Sweden      Entregatan 7   
124                                                nan      Entregatan 7   
131  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
132                                                nan               nan   
136  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
147  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
151  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
152  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   

     attendees   attendee_type                  call_focus       call_method  \
95         0.0  Person Account  Non-promotional discussion   Voice-only Call   
97         0.0  Person Account  Non-promotional discussion   Voice-only Call   
105        0.0  Person Account  Non-promotional discussion     Virtual Other   
119        0.0  Person Account  Non-promotional discussion  Virtual MS Teams   
120        0.0  Person Account  Non-promotional discussion  Virtual MS Teams   
124        0.0  Person Account                         NaN  Virtual MS Teams   
131        0.0  Person Account  Non-promotional discussion   Voice-only Call   
132        0.0  Person Account                         NaN   Voice-only Call   
136        0.0  Person Account  Non-promotional discussion     Virtual Other   
147        0.0  Person Account  Non-promotional discussion     Virtual Other   
151        0.0  Person Account  Non-promotional discussion     Virtual Other   
152        0.0  Person Account  Non-promotional discussion     Virtual Other   

     duration_in_minutes       account_id indication  
95                  30.0  0012o00002iEVhC   Melanoma  
97                  30.0  0012o00002iELPE   Melanoma  
105                 30.0  0012o00002iELPE   Melanoma  
119                  NaN  0012o00002iELPE   Melanoma  
120                 30.0  0012o00002iELPE   Melanoma  
124                 90.0  0012o00002iEVhC   Melanoma  
131                  NaN  0012o00002iELPE   Melanoma  
132                 10.0  0012o00002iEVhC   Melanoma  
136                 30.0  0012o00002iELPE   Melanoma  
147                 30.0  0012o00002iELPE   Melanoma  
151 

Hanna Eriksson works at Karolinska Univ Sjh Solna. Look [here](https://www.aminer.cn/profile/hanna-eriksson/560adc8b45ce1e595ff7d2c1).

#### Muhammad Kadum

In [13]:
calls_subset[calls_subset['account_name'] == 'Muhammad Kadum']

call_name account_record_type parent_call       date  \
76   C007594422                 HCP         0.0 2020-11-12   
115  C009443401                 HCP         1.0 2021-05-21   

               datetime    account_name  \
76  2020-11-12 15:00:00  Muhammad Kadum   
115 2021-05-21 08:45:00  Muhammad Kadum   

                                               address      address_line_1  \
76   J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29...  J A Hedlunds Väg 5   
115         Entregatan 7, LUND, Skåne län 22241 Sweden        Entregatan 7   

     attendees   attendee_type              call_focus           call_method  \
76         0.0  Person Account  Promotional discussion  Virtual Veeva Engage   
115        0.0  Person Account  Promotional discussion         Virtual Other   

     duration_in_minutes       account_id indication  
76                   NaN  0012o00002kTnsd         BC  
115                 30.0  0012o00002kTnsd         BC

Muhammad Kadum works at Lund University. Look [here](https://www.lunduniversity.lu.se/lucat/group/v1001367).

### II. NaN's

When looking though the data frame, we see that a lot of missing values exist for the addresses/hospitals.

In [14]:
calls_subset[calls_subset['address'] == 'nan'].sort_values(by='account_name')

call_name account_record_type parent_call       date  \
55   C005688057                 HCP         1.0 2020-09-09   
149  C010218246                 HCP         1.0 2021-08-24   
148  C009729312                 HCP         1.0 2021-06-22   
86   C009584476                 HCP         1.0 2021-02-10   
81   C009586775                 HCP         1.0 2021-01-28   
77   C009586858                 HCP         1.0 2020-11-23   
93   C009587559                 HCP         1.0 2021-03-30   
68   C009587502                 HCP         1.0 2020-10-12   
74   C009587636                 HCP         1.0 2020-10-19   
102  C009587720                 HCP         1.0 2021-04-27   
132  C009582426                 HCP         1.0 2021-06-04   
124  C009541730                 HCP         0.0 2021-05-27   
98   C009587977                 HCP         1.0 2021-04-20   
92   C009588085                 HCP         1.0 2021-03-18   
108  C009466569                 HCP         1.0 2021-05-17   
80   C009588246                 HCP         1.0 2021-01-13   
100  C009588280                 HCP         1.0 2021-04-23   
113  C009466447                 HCP         0.0 2021-05-20   
169  C010445491                 HCP         1.0 2021-09-15   
123  C009541764                 HCP         0.0 2021-05-27   
56   C005688076                 HCP         1.0 2020-09-09   
90   C009588668                 HCP         1.0 2021-03-08   
89   C009588533                 HCP         1.0 2021-02-22   
153  C010298252                 HCP         1.0 2021-09-02   
79   C009592406                 HCP         1.0 2020-12-18   

               datetime                      account_name address  \
55  2020-09-09 21:25:00  Ana Sequeira De V. Dias Carneiro     nan   
149 2021-08-24 14:20:00  Ana Sequeira De V. Dias Carneiro     nan   
148 2021-06-22 16:30:00  Ana Sequeira De V. Dias Carneiro     nan   
86  2021-02-10 15:00:00  Ana Sequeira De V. Dias Carneiro     nan   
81  2021-01-28 16:00:00  Ana Sequeira De V. Dias Carneiro     nan   
77  2020-11-23 14:00:00                   Bengt Tholander     nan   
93  2021-03-30 17:00:00                    Björn Båtshake     nan   
68  2020-10-12 16:00:00                    Björn Båtshake     nan   
74  2020-10-19 11:00:00                  Björn Sigurdsson     nan   
102 2021-04-27 15:00:00                 Eva Marie Erfurth     nan   
132 2021-06-04 16:30:00                    Hanna Eriksson     nan   
124 2021-05-27 17:00:00                    Hanna Eriksson     nan   
98  2021-04-20 13:00:00                      Helena Mörse     nan   
92  2021-03-18 15:30:00                  Ingrid Rosengren     nan   
108 2021-05-17 10:00:00                   Jeffrey Yachnin     nan   
80  2021-01-13 11:00:00                     Johan Malmros     nan   
100 2021-04-23 11:00:00                  Josefin Fernebro     nan   
113 2021-05-20 17:00:00                      Karin Hallen     nan   
169 2021-09-15 08:30:00                       Lars Hjorth     nan   
123 2021-05-27 17:00:00                      Lars Larsson     nan   
56  2020-09-09 21:27:00                      Magnus Sabel     nan   
90  2021-03-08 08:39:00                         Per Nyman     nan   
89  2021-02-22 09:30:00                         Per Nyman     nan   
153 2021-09-02 10:00:00                   Petter Svenberg     nan   
79  2020-12-18 16:00:00        Tatiana von Bahr Greenwood     nan   

      address_line_1  attendees   attendee_type call_focus       call_method  \
55               nan        0.0  Person Account        NaN               NaN   
149              nan        0.0  Person Account        NaN   Voice-only Call   
148              nan        0.0  Person Account        NaN   Voice-only Call   
86               nan        0.0  Person Account        NaN  Virtual MS Teams   
81               nan        0.0  Person Account        NaN   Voice-only Call   
77               nan        0.0  Person Account        NaN   Voice-only Call   
93               nan        0.0  Perso

Let us take a closer look at these cases.

#### Ana Sequeira De V. Dias Carneiro

In [15]:
calls_subset[calls_subset['account_name'] == 'Ana Sequeira De V. Dias Carneiro']

call_name account_record_type parent_call       date  \
55   C005688057                 HCP         1.0 2020-09-09   
81   C009586775                 HCP         1.0 2021-01-28   
86   C009584476                 HCP         1.0 2021-02-10   
148  C009729312                 HCP         1.0 2021-06-22   
149  C010218246                 HCP         1.0 2021-08-24   

               datetime                      account_name address  \
55  2020-09-09 21:25:00  Ana Sequeira De V. Dias Carneiro     nan   
81  2021-01-28 16:00:00  Ana Sequeira De V. Dias Carneiro     nan   
86  2021-02-10 15:00:00  Ana Sequeira De V. Dias Carneiro     nan   
148 2021-06-22 16:30:00  Ana Sequeira De V. Dias Carneiro     nan   
149 2021-08-24 14:20:00  Ana Sequeira De V. Dias Carneiro     nan   

    address_line_1  attendees   attendee_type call_focus       call_method  \
55             nan        0.0  Person Account        NaN               NaN   
81             nan        0.0  Person Account        NaN   Voice-only Call   
86             nan        0.0  Person Account        NaN  Virtual MS Teams   
148            nan        0.0  Person Account        NaN   Voice-only Call   
149            nan        0.0  Person Account        NaN   Voice-only Call   

     duration_in_minutes       account_id indication  
55                  30.0  0012o00002iERoC   Melanoma  
81                  20.0  0012o00002iERoC   Melanoma  
86                  30.0  0012o00002iERoC   Melanoma  
148                 20.0  0012o00002iERoC   Melanoma  
149                 30.0  0012o00002iERoC   Melanoma

Ana Sequeira De V. Dias Carneiro works at Lund Universitet. Look [here](https://portal.research.lu.se/en/persons/ana-carneiro).

#### Bengt Tholander

In [16]:
calls_subset[calls_subset['account_name'] == 'Bengt Tholander']

call_name account_record_type parent_call       date            datetime  \
77  C009586858                 HCP         1.0 2020-11-23 2020-11-23 14:00:00   

       account_name address address_line_1  attendees   attendee_type  \
77  Bengt Tholander     nan            nan        0.0  Person Account   

   call_focus      call_method  duration_in_minutes       account_id  \
77        NaN  Voice-only Call                 20.0  0012o00002kTDdr   

   indication  
77   Melanoma

Bengt Tholander works at Akademiska sjukhuset. Look [here](https://katalog.uu.se/profile/?id=N96-5347).

#### Björn Båtshake

In [15]:
calls_subset[calls_subset['account_name'] == 'Björn Båtshake']

call_name account_record_type parent_call       date            datetime  \
68  C009587502                 HCP         1.0 2020-10-12 2020-10-12 16:00:00   
93  C009587559                 HCP         1.0 2021-03-30 2021-03-30 17:00:00   

      account_name address address_line_1  attendees   attendee_type  \
68  Björn Båtshake     nan            nan        0.0  Person Account   
93  Björn Båtshake     nan            nan        0.0  Person Account   

   call_focus      call_method  duration_in_minutes       account_id  \
68        NaN  Voice-only Call                 30.0  0012o00002kTnIb   
93        NaN  Voice-only Call                 20.0  0012o00002kTnIb   

   indication  
68   Melanoma  
93   Melanoma

Björn Båtshake works at Lund Universitet. Look [here](https://lu.academia.edu/Bj%C3%B6rnB%C3%A5tshake).

#### Björn Sigurdsson (already looked at, but not with respect to NaN)

In [16]:
calls_subset[calls_subset['account_name'] == 'Björn Sigurdsson']

call_name account_record_type parent_call       date            datetime  \
35  C004371901                 HCP         0.0 2020-06-03 2020-06-03 11:01:00   
45  C005656684                 HCP         1.0 2020-08-25 2020-08-25 14:30:00   
65  C005889050                 HCP         1.0 2020-09-29 2020-09-29 14:00:00   
74  C009587636                 HCP         1.0 2020-10-19 2020-10-19 11:00:00   

        account_name                                            address  \
35  Björn Sigurdsson  Barn- och ungdomsmedicin, Jan Waldenströms gat...   
45  Björn Sigurdsson                        SE-Arbetsplats okänd Sweden   
65  Björn Sigurdsson                        SE-Arbetsplats okänd Sweden   
74  Björn Sigurdsson                                                nan   

              address_line_1  attendees   attendee_type call_focus  \
35  Jan Waldenströms gata 18        0.0  Person Account        NaN   
45      SE-Arbetsplats okänd        0.0  Person Account        NaN   
65      SE-Arbetsplats okänd        0.0  Person Account        NaN   
74                       nan        0.0  Person Account        NaN   

        call_method  duration_in_minutes       account_id indication  
35            Phone                 30.0  0012o00002iEYtq   Melanoma  
45              NaN                 30.0  0012o00002iEYtq   Melanoma  
65            Phone                 30.0  0012o00002iEYtq   Melanoma  
74  Voice-only Call                 20.0  0012o00002iEYtq   Melanoma

In [17]:
calls_subset['address'][35]

'Barn- och ungdomsmedicin, Jan Waldenströms gata 18, MALMÖ 21428'

Björn Sigursson works in Malmö.

#### Eva Marie Erfurth

In [18]:
calls_subset[calls_subset['account_name'] == 'Eva Marie Erfurth']

call_name account_record_type parent_call       date  \
102  C009587720                 HCP         1.0 2021-04-27   

               datetime       account_name address address_line_1  attendees  \
102 2021-04-27 15:00:00  Eva Marie Erfurth     nan            nan        0.0   

      attendee_type call_focus      call_method  duration_in_minutes  \
102  Person Account        NaN  Voice-only Call                 15.0   

          account_id indication  
102  0012o00002iEPpz   Melanoma

Eva Marie Erfurth works at Lund Universitet. Look [here](https://www.lunduniversity.lu.se/lucat/user/429358f644db831460905685bbd707e1).

#### Hanna Eriksson

In [19]:
calls_subset[calls_subset['account_name'] == 'Hanna Eriksson']

call_name account_record_type parent_call       date  \
95   C009537214                 HCP         1.0 2021-04-06   
97   C009318413                 HCP         1.0 2021-04-20   
105  C009318244                 HCP         1.0 2021-05-05   
119  C009458860                 HCP         0.0 2021-05-25   
120  C009485879                 HCP         0.0 2021-05-27   
124  C009541730                 HCP         0.0 2021-05-27   
131  C009602973                 HCP         0.0 2021-06-02   
132  C009582426                 HCP         1.0 2021-06-04   
136  C009840057                 HCP         1.0 2021-06-16   
147  C009840065                 HCP         1.0 2021-06-21   
151  C010297220                 HCP         1.0 2021-08-30   
152  C010301595                 HCP         1.0 2021-09-02   

               datetime    account_name  \
95  2021-04-06 15:29:00  Hanna Eriksson   
97  2021-04-20 08:00:00  Hanna Eriksson   
105 2021-05-05 08:00:00  Hanna Eriksson   
119 2021-05-25 15:10:00  Hanna Eriksson   
120 2021-05-27 17:00:00  Hanna Eriksson   
124 2021-05-27 17:00:00  Hanna Eriksson   
131 2021-06-02 09:00:00  Hanna Eriksson   
132 2021-06-04 16:30:00  Hanna Eriksson   
136 2021-06-16 08:00:00  Hanna Eriksson   
147 2021-06-21 08:00:00  Hanna Eriksson   
151 2021-08-30 08:00:00  Hanna Eriksson   
152 2021-09-02 08:00:00  Hanna Eriksson   

                                               address    address_line_1  \
95   Eugeniavägen 3, SOLNA, Stockholms län A-B 1716...    Eugeniavägen 3   
97   Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
105  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
119  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
120         Entregatan 7, LUND, Skåne län 22241 Sweden      Entregatan 7   
124                                                nan      Entregatan 7   
131  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
132                                                nan               nan   
136  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
147  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
151  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   
152  Karolinska Vägen, SOLNA, Stockholms län A-B 17...  Karolinska Vägen   

     attendees   attendee_type                  call_focus       call_method  \
95         0.0  Person Account  Non-promotional discussion   Voice-only Call   
97         0.0  Person Account  Non-promotional discussion   Voice-only Call   
105        0.0  Person Account  Non-promotional discussion     Virtual Other   
119        0.0  Person Account  Non-promotional discussion  Virtual MS Teams   
120        0.0  Person Account  Non-promotional discussion  Virtual MS Teams   
124        0.0  Person Account                         NaN  Virtual MS Teams   
131        0.0  Person Account  Non-promotional discussion   Voice-only Call   
132        0.0  Person Account                         NaN   Voice-only Call   
136        0.0  Person Account  Non-promotional discussion     Virtual Other   
147        0.0  Person Account  Non-promotional discussion     Virtual Other   
151        0.0  Person Account  Non-promotional discussion     Virtual Other   
152        0.0  Person Account  Non-promotional discussion     Virtual Other   

     duration_in_minutes       account_id indication  
95                  30.0  0012o00002iEVhC   Melanoma  
97                  30.0  0012o00002iELPE   Melanoma  
105                 30.0  0012o00002iELPE   Melanoma  
119                  NaN  0012o00002iELPE   Melanoma  
120                 30.0  0012o00002iELPE   Melanoma  
124                 90.0  0012o00002iEVhC   Melanoma  
131                  NaN  0012o00002iELPE   Melanoma  
132                 10.0  0012o00002iEVhC   Melanoma  
136                 30.0  0012o00002iELPE   Melanoma  
147                 30.0  0012o00002iELPE   Melanoma  
151 

Hanna Eriksson works at Karolinska Univ Sjh Solna. Look [here](https://www.aminer.cn/profile/hanna-eriksson/560adc8b45ce1e595ff7d2c1).

#### Helena Mörse

In [20]:
calls_subset[calls_subset['account_name'] == 'Helena Mörse']

call_name account_record_type parent_call       date            datetime  \
57  C005729169                 HCP         1.0 2020-09-14 2020-09-14 13:25:00   
98  C009587977                 HCP         1.0 2021-04-20 2021-04-20 13:00:00   

    account_name                                          address  \
57  Helena Mörse  Lasarettsgatan 48, LUND, Skåne län 22241 Sweden   
98  Helena Mörse                                              nan   

       address_line_1  attendees   attendee_type call_focus      call_method  \
57  Lasarettsgatan 48        0.0  Person Account        NaN            Email   
98                nan        0.0  Person Account        NaN  Voice-only Call   

    duration_in_minutes       account_id indication  
57                 30.0  0012o00002iEPCw   Melanoma  
98                 20.0  0012o00002iEPCw   Melanoma

Helena Mörse works at Lund Universitet. Look [here](https://www.lunduniversity.lu.se/lucat/user/946a897a097432b68336d78e1f42dcb5).

#### Ingrid Rosengren

In [21]:
calls_subset[calls_subset['account_name'] == 'Ingrid Rosengren']

call_name account_record_type parent_call       date            datetime  \
92  C009588085                 HCP         1.0 2021-03-18 2021-03-18 15:30:00   

        account_name address address_line_1  attendees   attendee_type  \
92  Ingrid Rosengren     nan            nan        0.0  Person Account   

   call_focus      call_method  duration_in_minutes       account_id  \
92        NaN  Voice-only Call                 20.0  0012o00002iERvP   

   indication  
92   Melanoma

There is no reliable info on the Internet on where Ingrid Rosengren works.

#### Jeffrey Yachnin

In [21]:
calls_subset[calls_subset['account_name'] == 'Jeffrey Yachnin']

call_name account_record_type parent_call       date  \
108  C009466569                 HCP         1.0 2021-05-17   

               datetime     account_name address address_line_1  attendees  \
108 2021-05-17 10:00:00  Jeffrey Yachnin     nan            nan        0.0   

      attendee_type call_focus      call_method  duration_in_minutes  \
108  Person Account        NaN  Voice-only Call                 30.0   

          account_id indication  
108  0012o00002iEazF   Melanoma

Jeffrey Yachnin works at Karolinska Univ Sjh Solna. Look [here](https://www.researchgate.net/profile/Jeffrey-Yachnin).

#### Johan Malmros

In [22]:
calls_subset[calls_subset['account_name'] == 'Johan Malmros']

call_name account_record_type parent_call       date            datetime  \
80  C009588246                 HCP         1.0 2021-01-13 2021-01-13 11:00:00   

     account_name address address_line_1  attendees   attendee_type  \
80  Johan Malmros     nan            nan        0.0  Person Account   

   call_focus      call_method  duration_in_minutes       account_id  \
80        NaN  Voice-only Call                 20.0  0012o00002kTCw2   

   indication  
80   Melanoma

Johan Malmros works at Karolinska Univ Sjh Solna. Look [here](https://www.researchgate.net/profile/Johan-Malmros).

#### Josefin Fernebro

In [23]:
calls_subset[calls_subset['account_name'] == 'Josefin Fernebro']

call_name account_record_type parent_call       date  \
100  C009588280                 HCP         1.0 2021-04-23   

               datetime      account_name address address_line_1  attendees  \
100 2021-04-23 11:00:00  Josefin Fernebro     nan            nan        0.0   

      attendee_type call_focus      call_method  duration_in_minutes  \
100  Person Account        NaN  Voice-only Call                 25.0   

          account_id indication  
100  0012o00002kT8rS   Melanoma

Josefin Fernebro works at Karolinska Univ Sjh Solna. Look [here](https://www.linkedin.com/in/josefin-fernebro-559264b5/?originalSubdomain=se).

#### Karin Hallen

In [24]:
calls_subset[calls_subset['account_name'] == 'Karin Hallen']

call_name account_record_type parent_call       date  \
113  C009466447                 HCP         0.0 2021-05-20   

               datetime  account_name address   address_line_1  attendees  \
113 2021-05-20 17:00:00  Karin Hallen     nan  Sjukhusvägen 85        0.0   

      attendee_type call_focus       call_method  duration_in_minutes  \
113  Person Account        NaN  Virtual MS Teams                 90.0   

          account_id indication  
113  0012o00002kTomM   Melanoma

'Sjukhusvägen 85' tells us that she Karin Hallen works at Akademiska sjukhuset in Uppsala. Look [here](https://www.google.de/search?q=sjukhusv%C3%A4gen+85&sxsrf=APq-WBuV9rhu8CZBdzhet_VC1QrV1zADKQ%3A1645458281521&ei=abMTYrK0H4ng7_UP_9eowA4&ved=0ahUKEwjyjPPikZH2AhUJ8LsIHf8rCugQ4dUDCA4&uact=5&oq=sjukhusv%C3%A4gen+85&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABKBAhGGABQAFgAYGVoAHAAeACAAQCIAQCSAQCYAQCgAQHAAQE&sclient=gws-wiz).

#### Lars Hjorth

In [25]:
calls_subset[calls_subset['account_name'] == 'Lars Hjorth']

call_name account_record_type parent_call       date  \
169  C010445491                 HCP         1.0 2021-09-15   

               datetime account_name address address_line_1  attendees  \
169 2021-09-15 08:30:00  Lars Hjorth     nan            nan        0.0   

      attendee_type call_focus      call_method  duration_in_minutes  \
169  Person Account        NaN  Voice-only Call                 15.0   

          account_id indication  
169  0012o00002iEeIV   Melanoma

Lars Hjorth works at Lund Universitet. Look [here](https://portal.research.lu.se/en/persons/lars-hjorth).

#### Lars Larsson

In [26]:
calls_subset[calls_subset['account_name'] == 'Lars Larsson']

call_name account_record_type parent_call       date  \
121  C009485880                 HCP         0.0 2021-05-27   
122  C009537186                 HCP         1.0 2021-05-27   
123  C009541764                 HCP         0.0 2021-05-27   

               datetime  account_name  \
121 2021-05-27 17:00:00  Lars Larsson   
122 2021-05-27 17:00:00  Lars Larsson   
123 2021-05-27 17:00:00  Lars Larsson   

                                               address     address_line_1  \
121         Entregatan 7, LUND, Skåne län 22241 Sweden       Entregatan 7   
122  Brämhultsvägen 53, BORÅS, Västra Götalands län...  Brämhultsvägen 53   
123                                                nan       Entregatan 7   

     attendees   attendee_type                  call_focus       call_method  \
121        0.0  Person Account  Non-promotional discussion  Virtual MS Teams   
122        0.0  Person Account  Non-promotional discussion  Virtual MS Teams   
123        0.0  Person Account                         NaN  Virtual MS Teams   

     duration_in_minutes       account_id indication  
121                 30.0  0012o00002iERpF   Melanoma  
122                 30.0  0012o00002iERpF   Melanoma  
123                 90.0  0012o00002iERpF   Melanoma

Lars Larsson works at Karolinska Univ Sjh Solna. Look [here](https://ki.se/en/mtc/lars-gunnar-larsson-group).

#### Magnus Sabel

In [27]:
calls_subset[calls_subset['account_name'] == 'Magnus Sabel']

call_name account_record_type parent_call       date            datetime  \
56  C005688076                 HCP         1.0 2020-09-09 2020-09-09 21:27:00   

    account_name address address_line_1  attendees   attendee_type call_focus  \
56  Magnus Sabel     nan            nan        0.0  Person Account        NaN   

   call_method  duration_in_minutes       account_id indication  
56         NaN                 30.0  0012o00002iEVSK   Melanoma

Magnus Sabel works at Sahlgrenska Univ sjh. Look [here](https://www.gu.se/en/about/find-staff/magnussabel).

#### Per Nyman

In [28]:
calls_subset[calls_subset['account_name'] == 'Per Nyman']

call_name account_record_type parent_call       date            datetime  \
89  C009588533                 HCP         1.0 2021-02-22 2021-02-22 09:30:00   
90  C009588668                 HCP         1.0 2021-03-08 2021-03-08 08:39:00   

   account_name address address_line_1  attendees   attendee_type call_focus  \
89    Per Nyman     nan            nan        0.0  Person Account        NaN   
90    Per Nyman     nan            nan        0.0  Person Account        NaN   

        call_method  duration_in_minutes       account_id indication  
89  Voice-only Call                 15.0  0012o00002iEaA9   Melanoma  
90  Voice-only Call                 15.0  0012o00002iEaA9   Melanoma

There is no reliable info on the Internet on where Per Nyman works.

#### Petter Svenberg

In [29]:
calls_subset[calls_subset['account_name'] == 'Petter Svenberg']

call_name account_record_type parent_call       date  \
153  C010298252                 HCP         1.0 2021-09-02   

               datetime     account_name address address_line_1  attendees  \
153 2021-09-02 10:00:00  Petter Svenberg     nan            nan        0.0   

      attendee_type call_focus      call_method  duration_in_minutes  \
153  Person Account        NaN  Voice-only Call                 10.0   

          account_id indication  
153  0012o00002iEcMf   Melanoma

Petter Svenberg works at Karolinska Univ Sjh Solna. Look [here](https://www.researchgate.net/profile/Petter-Svenberg).

#### Tatiana von Bahr Greenwood

In [30]:
calls_subset[calls_subset['account_name'] == 'Tatiana von Bahr Greenwood']

call_name account_record_type parent_call       date            datetime  \
79  C009592406                 HCP         1.0 2020-12-18 2020-12-18 16:00:00   

                  account_name address address_line_1  attendees  \
79  Tatiana von Bahr Greenwood     nan            nan        0.0   

     attendee_type call_focus      call_method  duration_in_minutes  \
79  Person Account        NaN  Voice-only Call                 20.0   

         account_id indication  
79  0012o00002kTCh9   Melanoma

Tatiana von Bahr Greenwood works at Karolinska Univ Sjh Solna. Look [here](https://www.medifind.com/doctors/tatiana-von-bahr-greenwood/312644782).

### III. Check of Hospitals

Take a look at the different hospitals given in `address`.

In [22]:
calls_subset['address'].unique().tolist()

['Onkologikliniken, Centrallasarettet 1, VÄSTERÅS 72335',
 'Onkologiska kliniken, Södra Grev Rosengatan, ÖREBRO 70362',
 'Medicin- och onkologkliniken, Brämhultsvägen 53, BORÅS 50455',
 'Kirurgkliniken, Lasarettsvägen, KARLSKRONA 37141',
 'Cancercentrum, Akutvägen, UMEÅ 90737',
 'Södra Älvsborgs Sjukhus Borås, Brämhultsvägen 53, BORÅS 50455',
 'Onkologkliniken, Sjukhusvägen 85, UPPSALA 75185',
 'Barn- och ungdomsmedicin, Jan Waldenströms gata 18, MALMÖ 21428',
 'Barn- och ungdomskliniken, Lasarettsvägen 21, SUNDSVALL 85643',
 'Barn- och ungdomskliniken, Lasarettsvägen 1, KALMAR 39244',
 'KFUE, Akademiska sjukhuset Ing 78 5 tr, UPPSALA 75185',
 'Apoteket Berguven, Lasarettsvägen, HALMSTAD 30233',
 'Barncancerenheten Q6:04, Eugeniavägen 23, SOLNA 17164',
 'SE-Arbetsplats okänd Sweden',
 'Akademiska sjukhuset Ing 78 5 tr, UPPSALA, Landstinget i Uppsala län 75185 Sweden',
 'Sjukhusbacken 10, STOCKHOLM, Stockholms läns landsting 11861 Sweden',
 'nan',
 'Lasarettsgatan 48, LUND, Skåne län 22

Looking at the addresses/hospitals, there are several things that come to attention:

* There are unknown hospitals: 'Hantverkargatan 25 B, STOCKHOLM, Stockholms län A-B 11221 Sweden', J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29133 Sweden', 'Hietalahdenkatu 2-4, Vaasa, Vaasa 65130 Finland'. (even a Finnish hospital is given)
* Some hospitals occur several times, but with different addresses. For instance, the hospital in Borås goes by the names of Medicin- och onkologkliniken, Brämhultsvägen 53, BORÅS 50455',  'Södra Älvsborgs Sjukhus Borås, Brämhultsvägen 53, BORÅS 50455' and  'Brämhultsvägen 53, BORÅS, Västra Götalands län 50455 Sweden'. 
* Remark: The 'Apoteket Berguven, Lasarettsvägen, HALMSTAD 30233' refers to Hallands sjukhus Halmstad.

Let us now take a look at these cases.

In [23]:
calls_subset[calls_subset['address'] == 'Hantverkargatan 25 B, STOCKHOLM, Stockholms län A-B 11221 Sweden']

call_name account_record_type parent_call       date  \
78   C007811437                 HCP         0.0 2020-12-02   
85   C008324018                 HCP         0.0 2021-02-09   
94   C009187916                 HCP         0.0 2021-03-31   
96   C009187924                 HCP         0.0 2021-04-18   
112  C009388980                 HCP         0.0 2021-05-19   
133  C009652889                 HCP         0.0 2021-06-14   

               datetime  account_name  \
78  2020-12-02 11:00:00  Marit Jenset   
85  2021-02-09 10:00:00  Marit Jenset   
94  2021-03-31 15:08:00  Marit Jenset   
96  2021-04-18 12:10:00  Marit Jenset   
112 2021-05-19 15:00:00  Marit Jenset   
133 2021-06-14 15:00:00  Marit Jenset   

                                               address        address_line_1  \
78   Hantverkargatan 25 B, STOCKHOLM, Stockholms lä...  Hantverkargatan 25 B   
85   Hantverkargatan 25 B, STOCKHOLM, Stockholms lä...  Hantverkargatan 25 B   
94   Hantverkargatan 25 B, STOCKHOLM, Stockholms lä...  Hantverkargatan 25 B   
96   Hantverkargatan 25 B, STOCKHOLM, Stockholms lä...  Hantverkargatan 25 B   
112  Hantverkargatan 25 B, STOCKHOLM, Stockholms lä...  Hantverkargatan 25 B   
133  Hantverkargatan 25 B, STOCKHOLM, Stockholms lä...  Hantverkargatan 25 B   

     attendees   attendee_type call_focus       call_method  \
78         0.0  Person Account        NaN  Virtual MS Teams   
85         0.0  Person Account        NaN  Virtual MS Teams   
94         0.0  Person Account        NaN             Email   
96         0.0  Person Account        NaN             Email   
112        0.0  Person Account        NaN  Virtual MS Teams   
133        0.0  Person Account        NaN     Virtual Other   

     duration_in_minutes       account_id indication  
78                  60.0  0012o00002iEXzz         BC  
85                  50.0  0012o00002iEXzz         BC  
94                  30.0  0012o00002iEXzz         BC  
96                  30.0  0012o00002iEXzz         BC  
112                 30.0  0012o00002iEXzz         BC  
133                 30.0  0012o00002iEXzz         BC

Marit Jenset is not an HCP. Look [here](https://www.linkedin.com/in/marit-jenset-65570212/?originalSubdomain=se).

In [24]:
calls_subset[calls_subset['address'] == 'J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29133 Sweden']

call_name account_record_type parent_call       date            datetime  \
75  C007594421                 HCP         0.0 2020-11-12 2020-11-12 15:00:00   
76  C007594422                 HCP         0.0 2020-11-12 2020-11-12 15:00:00   

      account_name                                            address  \
75   Lena Axelsson  J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29...   
76  Muhammad Kadum  J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29...   

        address_line_1  attendees   attendee_type              call_focus  \
75  J A Hedlunds Väg 5        0.0  Person Account  Promotional discussion   
76  J A Hedlunds Väg 5        0.0  Person Account  Promotional discussion   

             call_method  duration_in_minutes       account_id indication  
75  Virtual Veeva Engage                  NaN  0012o00002kTBuS         BC  
76  Virtual Veeva Engage                  NaN  0012o00002kTnsd         BC

This address belongs to Centralsjukhuset Kristianstad. 

In [25]:
calls_subset[calls_subset['account_name'] == 'Lena Axelsson']

call_name account_record_type parent_call       date            datetime  \
75  C007594421                 HCP         0.0 2020-11-12 2020-11-12 15:00:00   

     account_name                                            address  \
75  Lena Axelsson  J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29...   

        address_line_1  attendees   attendee_type              call_focus  \
75  J A Hedlunds Väg 5        0.0  Person Account  Promotional discussion   

             call_method  duration_in_minutes       account_id indication  
75  Virtual Veeva Engage                  NaN  0012o00002kTBuS         BC

Lena Axelsson works at Lund university. Look [here](https://portal.research.lu.se/en/persons/lena-axelsson).

In [26]:
calls_subset[calls_subset['account_name'] == 'Muhammad Kadum']

call_name account_record_type parent_call       date  \
76   C007594422                 HCP         0.0 2020-11-12   
115  C009443401                 HCP         1.0 2021-05-21   

               datetime    account_name  \
76  2020-11-12 15:00:00  Muhammad Kadum   
115 2021-05-21 08:45:00  Muhammad Kadum   

                                               address      address_line_1  \
76   J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29...  J A Hedlunds Väg 5   
115         Entregatan 7, LUND, Skåne län 22241 Sweden        Entregatan 7   

     attendees   attendee_type              call_focus           call_method  \
76         0.0  Person Account  Promotional discussion  Virtual Veeva Engage   
115        0.0  Person Account  Promotional discussion         Virtual Other   

     duration_in_minutes       account_id indication  
76                   NaN  0012o00002kTnsd         BC  
115                 30.0  0012o00002kTnsd         BC

Muhammad Kadum works at Lund university. Look [here](https://www.lunduniversity.lu.se/lucat/group/v1001367).

In [27]:
calls_subset[calls_subset['address'] == 'Hietalahdenkatu 2-4, Vaasa, Vaasa 65130 Finland']

call_name account_record_type parent_call       date  \
160  C010353070                 HCP         0.0 2021-09-08   

               datetime   account_name  \
160 2021-09-08 11:00:00  Jonathan Lind   

                                             address       address_line_1  \
160  Hietalahdenkatu 2-4, Vaasa, Vaasa 65130 Finland  Hietalahdenkatu 2-4   

     attendees   attendee_type              call_focus       call_method  \
160        0.0  Person Account  Promotional discussion  Virtual MS Teams   

     duration_in_minutes       account_id indication  
160                 30.0  0012o00002iEYBQ         BC

In [28]:
calls_subset[calls_subset['account_name'] == 'Jonathan Lind']

call_name account_record_type parent_call       date  \
160  C010353070                 HCP         0.0 2021-09-08   

               datetime   account_name  \
160 2021-09-08 11:00:00  Jonathan Lind   

                                             address       address_line_1  \
160  Hietalahdenkatu 2-4, Vaasa, Vaasa 65130 Finland  Hietalahdenkatu 2-4   

     attendees   attendee_type              call_focus       call_method  \
160        0.0  Person Account  Promotional discussion  Virtual MS Teams   

     duration_in_minutes       account_id indication  
160                 30.0  0012o00002iEYBQ         BC

In our project, we are only looking at Sweden. So, Jonathan Lind and the corresponding Finnish hospital are removed.
In addition, there is no reliable info on the internet on where Jonathan Lind is working (as BC HCP in Sweden or Finland).

In order to make sure that two different addresses which refer to the same hospital are identical, we create `address_mapping_dict`, a dictionary that assigns the same address to addresses which refer to the same hospital. These addresses are the same also used above for the targets data frame.

In [29]:
address_mapping_dict = {
    'Onkologikliniken, Centrallasarettet 1, VÄSTERÅS 72335': 'Sigtunagatan, 721 89 Västerås, Schweden',
    'Onkologiska kliniken, Södra Grev Rosengatan, ÖREBRO 70362': 'Södra Grev Rosengatan, 701 85 Örebro, Schweden',
    'Medicin- och onkologkliniken, Brämhultsvägen 53, BORÅS 50455': 'Brämhultsvägen 53, 501 82 Borås, Schweden',
    'Kirurgkliniken, Lasarettsvägen, KARLSKRONA 37141': 'Lasarettsvägen, 371 41 Karlskrona, Schweden',
    'Cancercentrum, Akutvägen, UMEÅ 90737': 'Daniel Naezéns väg, 907 37 Umeå, Schweden',
    'Södra Älvsborgs Sjukhus Borås, Brämhultsvägen 53, BORÅS 50455': 'Brämhultsvägen 53, 501 82 Borås, Schweden',
    'Onkologkliniken, Sjukhusvägen 85, UPPSALA 75185': 'Sjukhusvägen, 751 85 Uppsala, Schweden',
    'Barn- och ungdomsmedicin, Jan Waldenströms gata 18, MALMÖ 21428': 'Carl-Bertil Laurells gata 9, 214 28 Malmö, Schweden',
    'Barn- och ungdomskliniken, Lasarettsvägen 21, SUNDSVALL 85643': 'Lasarettsvägen 21, 856 43 Sundsvall, Schweden',
    'Barn- och ungdomskliniken, Lasarettsvägen 1, KALMAR 39244': 'Lasarettsvägen 8, 392 44 Kalmar, Schweden',
    'KFUE, Akademiska sjukhuset Ing 78 5 tr, UPPSALA 75185': 'Sjukhusvägen, 751 85 Uppsala, Schweden',
    'Apoteket Berguven, Lasarettsvägen, HALMSTAD 30233': 'Lasarettsvägen, 302 33 Halmstad, Schweden',
    'Barncancerenheten Q6:04, Eugeniavägen 23, SOLNA 17164': 'Eugeniavägen 3, 171 64 Solna, Schweden',
    'Akademiska sjukhuset Ing 78 5 tr, UPPSALA, Landstinget i Uppsala län 75185 Sweden': 'Sjukhusvägen, 751 85 Uppsala, Schweden',
    'Sjukhusbacken 10, STOCKHOLM, Stockholms läns landsting 11861 Sweden': 'Sjukhusbacken 10, 118 83 Stockholm, Schweden',
    #'nan',
    'Lasarettsgatan 48, LUND, Skåne län 22241 Sweden': 'Entrégatan 7, 222 42 Lund, Schweden',
    'S:t Göransgatan 5, VISBY, Gotlands kommun 62155 Sweden': 'S:t Göransgatan 5, 621 55 Visby, Schweden',
    'Eugeniavägen 23, SOLNA, Stockholms läns landsting 17164 Sweden': 'Eugeniavägen 3, 171 64 Solna, Schweden',
    'Sankt Göransplan 1, STOCKHOLM, Stockholms läns landsting 11281': 'Sankt Göransplan 1, 112 19 Stockholm, Schweden',
    'Rosenborgsgatan 2, KARLSTAD, Landstinget i Värmland 65230 Sweden': 'Rosenborgsgatan 9, 652 30 Karlstad, Schweden',
    'J A Hedlunds Väg 5, KRISTIANSTAD, Skåne län 29133 Sweden':  'Lund, Schweden', 
    'Mellbygatan 11-13, LIDKÖPING, Västra Götalands län 53151 Sweden': 'Mellbygatan 11, 531 51 Lidköping, Schweden',
    'Kungsvägen, ESKILSTUNA, Södermanlands län D 63340 Sweden': 'Kungsvägen 42, 633 49 Eskilstuna, Schweden',
    'Blå Stråket 6, GÖTEBORG, Västra Götalands län 41346 Sweden': 'Blå stråket 5, 413 45 Göteborg, Schweden',
    'Eugeniavägen 3, SOLNA, Stockholms län A-B 17164 Sweden': 'Eugeniavägen 3, 171 64 Solna, Schweden',
    'Karolinska Vägen, SOLNA, Stockholms län A-B 17165 Sweden': 'Eugeniavägen 3, 171 64 Solna, Schweden',
    'Rosenborgsgatan 2, KARLSTAD, Värmlands län S 65230 Sweden': 'Rosenborgsgatan 9, 652 30 Karlstad, Schweden',
    'Akutvägen, UMEÅ, Västerbottens län AC 90737 Sweden': 'Daniel Naezéns väg, 907 37 Umeå, Schweden',
    'Entregatan 7, LUND, Skåne län 22241 Sweden': 'Entrégatan 7, 222 42 Lund, Schweden',
    'Lasarettsvägen, KARLSKRONA, Blekinge län K 37141 Sweden': 'Lasarettsvägen, 371 41 Karlskrona, Schweden',
    'Charlotte Yhlens gata 10, HELSINGBORG, Skåne län 25223 Sweden': 'Charlotte Yhlens gata 10, 252 23 Helsingborg, Schweden',
    'Strandvägen 8, VÄXJÖ, Kronobergs län G 35234 Sweden': 'Strandvägen 8, 352 34 Växjö, Schweden',
    'Blå stråket 6, GÖTEBORG, Västra Götalands län 41346 Sweden': 'Blå stråket 5, 413 45 Göteborg, Schweden',
    'Brämhultsvägen 53, BORÅS, Västra Götalands län 50455 Sweden': 'Brämhultsvägen 53, 501 82 Borås, Schweden',
    'Lövängsvägen, SKÖVDE, Västra Götalands län 54142 Sweden': 'Lövängsvägen, 541 42 Skövde, Schweden',
    'Valhallavägen 91, STOCKHOLM, Stockholms län A-B 11428 Sweden': 'Valhallavägen 91, 114 86 Stockholm, Schweden',
    'Lasarettsvägen 1, KALMAR, Kalmar län H 39244 Sweden': 'Lasarettsvägen 8, 392 44 Kalmar, Schweden',
    'Centrallasarettet 1, VÄSTERÅS, Västmanlands län U 72335 Sweden': 'Sigtunagatan, 721 89 Västerås, Schweden',
    'Lasarettsvägen 21, SUNDSVALL, Västernorrlands län Y 85643 Sweden': 'Lasarettsvägen 21, 856 43 Sundsvall, Schweden',
    'Garnisonsvägen 10, LINKÖPING, Östergötlands län E 58750 Sweden': 'Universitetssjukhuset, 581 85 Linköping, Schweden'}

We now assign the new addresses to the old addresses.

In [30]:
calls_subset['address'] = calls_subset['address'].apply(lambda x: address_mapping_dict.get(x))

In addition, we do the following steps:
* correct multiple assigments
* plug in information for NaN's in `address` and delete HCPs for whom no information could be found
* correct unknown hospitals (delete Marit Jenset, correct hospital of Lena Axelsson, delete Jonathan Lind)

In [31]:
# correct multiple assigments
calls_subset.loc[calls_subset['account_name'] == 'Björn Sigurdsson', ['address']] = 'Carl-Bertil Laurells gata 9, 214 28 Malmö, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Hanna Eriksson', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Muhammad Kadum', ['address']] = 'Lund, Schweden'

# plug in information for nan's
calls_subset.loc[calls_subset['account_name'] == 'Ana Sequeira De V. Dias Carneiro', ['address']] = 'Lund, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Bengt Tholander', ['address']] = 'Sjukhusvägen, 751 85 Uppsala, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Björn Båtshake', ['address']] = 'Lund, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Eva Marie Erfurth', ['address']] = 'Lund, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Helena Mörse', ['address']] = 'Lund, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Jeffrey Yachnin', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Johan Malmros', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Josefin Fernebro', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Karin Hallen', ['address']] = 'Sjukhusvägen, 751 85 Uppsala, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Lars Hjorth', ['address']] = 'Lund, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Lars Larsson', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Magnus Sabel', ['address']] = 'Blå stråket 5, 413 45 Göteborg, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Petter Svenberg', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
calls_subset.loc[calls_subset['account_name'] == 'Tatiana von Bahr Greenwood', ['address']] = 'Eugeniavägen 3, 171 64 Solna, Schweden'
# delete 'Ingrid Rosengren'
calls_subset = calls_subset[calls_subset['account_name'] != 'Ingrid Rosengren']
# delete 'Per Nyman'
calls_subset = calls_subset[calls_subset['account_name'] != 'Per Nyman']

# correct unknown hospitals
# delete Marit Jenset
calls_subset = calls_subset[calls_subset['account_name'] != 'Marit Jenset']
# correct hospital for Lena Axelsson
calls_subset.loc[calls_subset['account_name'] == 'Lena Axelsson', ['address']] = 'Lund, Schweden'
# delete Jonathan Lind
calls_subset = calls_subset[calls_subset['account_name'] != 'Jonathan Lind']

calls_subset

call_name account_record_type parent_call       date  \
0    C004360771                 HCP         0.0 2020-01-16   
1    C004360773                 HCP         0.0 2020-01-16   
2    C004360776                 HCP         0.0 2020-01-16   
3    C004360777                 HCP         0.0 2020-01-16   
4    C004360780                 HCP         0.0 2020-01-16   
..          ...                 ...         ...        ...   
174  C010427094                 HCP         0.0 2021-09-15   
175  C010427095                 HCP         0.0 2021-09-15   
176  C010427096                 HCP         0.0 2021-09-15   
177  C010427097                 HCP         0.0 2021-09-15   
178  C010427098                 HCP         0.0 2021-09-15   

               datetime       account_name  \
0   2020-01-16 21:17:00      David Sterner   
1   2020-01-16 21:17:00      Lars Sandberg   
2   2020-01-16 21:17:00     Cecilia Kamali   
3   2020-01-16 21:17:00      Åsa Jonforsen   
4   2020-01-16 21:17:00    David Goldstein   
..                  ...                ...   
174 2021-09-15 12:00:00   Pernilla Nilsson   
175 2021-09-15 12:00:00   Sandra Sjöstrand   
176 2021-09-15 12:00:00       Pia Törnblom   
177 2021-09-15 12:00:00  Karolina Vernmark   
178 2021-09-15 12:00:00      Maria Östlund   

                                               address       address_line_1  \
0              Sigtunagatan, 721 89 Västerås, Schweden  Centrallasarettet 1   
1              Sigtunagatan, 721 89 Västerås, Schweden  Centrallasarettet 1   
2              Sigtunagatan, 721 89 Västerås, Schweden  Centrallasarettet 1   
3              Sigtunagatan, 721 89 Västerås, Schweden  Centrallasarettet 1   
4              Sigtunagatan, 721 89 Västerås, Schweden  Centrallasarettet 1   
..                                                 ...                  ...   
174  Universitetssjukhuset, 581 85 Linköping, Schweden    Garnisonsvägen 10   
175  Universitetssjukhuset, 581 85 Linköping, Schweden    Garnisonsvägen 10   
176  Universitetssjukhuset, 581 85 Linköping, Schweden    Garnisonsvägen 10   
177  Universitetssjukhuset, 581 85 Linköping, Schweden    Garnisonsvägen 10   
178  Universitetssjukhuset, 581 85 Linköping, Schweden    Garnisonsvägen 10   

     attendees   attendee_type              call_focus       call_method  \
0          0.0  Person Account  Promotional discussion      Face to Face   
1          0.0  Person Account  Promotional discussion      Face to Face   
2          0.0  Person Account  Promotional discussion      Face to Face   
3          0.0  Person Account  Promotional discussion      Face to Face   
4          0.0  Person Account  Promotional discussion      Face to Face   
..         ...             ...                     ...               ...   
174        0.0  Person Account  Promotional discussion  Virtual MS Teams   
175        0.0  Person Account  Promotional discussion  Virtual MS Teams   
176        0.0  Person Account  Promotional discussion  Virtual MS Teams   
177        0.0  Person Account  Promotional discussion  Virtual MS Teams   
178        0.0  Person Account  Promotional discussion  Virtual MS Teams   

     duration_in_minutes       account_id indication  
0                   30.0  0012o00002kTsAl   Melanoma  
1                   30.0  0012o00002iEVS2   Melanoma  
2                   30.0  0012o00002iDoJT   Melanoma  
3                   30.0  0012o00002iEWSI   Melanoma  
4                   30.0  0012o00002kTlW5   Melanoma  
..                   ...              ...        ...  
174                 45.0  0012o00002kTp20   Melanoma  
175                 45.0  0012o00002iEdyx   Melanoma  
176                 45.0  0012o00002iDrMc   Melanoma  
177                 45.0  0012o00002iEQjh   Melanoma  
178                 45.0  0012o00002iEdj0   Melanoma  

[169 rows x 15 columns]

The relevant columns to get the number of hospitals and HCPs in the BC and Melanoma regions are `account_name`, `address`, `indication`. We therefore select these columns now.

In [32]:
calls_subset = calls_subset.filter(items=['account_name', 'address', 'indication'])
calls_subset

account_name                                            address  \
0        David Sterner            Sigtunagatan, 721 89 Västerås, Schweden   
1        Lars Sandberg            Sigtunagatan, 721 89 Västerås, Schweden   
2       Cecilia Kamali            Sigtunagatan, 721 89 Västerås, Schweden   
3        Åsa Jonforsen            Sigtunagatan, 721 89 Västerås, Schweden   
4      David Goldstein            Sigtunagatan, 721 89 Västerås, Schweden   
..                 ...                                                ...   
174   Pernilla Nilsson  Universitetssjukhuset, 581 85 Linköping, Schweden   
175   Sandra Sjöstrand  Universitetssjukhuset, 581 85 Linköping, Schweden   
176       Pia Törnblom  Universitetssjukhuset, 581 85 Linköping, Schweden   
177  Karolina Vernmark  Universitetssjukhuset, 581 85 Linköping, Schweden   
178      Maria Östlund  Universitetssjukhuset, 581 85 Linköping, Schweden   

    indication  
0     Melanoma  
1     Melanoma  
2     Melanoma  
3     Melanoma  
4     Melanoma  
..         ...  
174   Melanoma  
175   Melanoma  
176   Melanoma  
177   Melanoma  
178   Melanoma  

[169 rows x 3 columns]

The data frame `calls_subset` is now prepared to be used for the HCP and hospital counts.

## 3. Calls: Count of calls for all the BC and Melanoma regions

In [33]:
targets_list = targets['account_name'].unique().tolist()

calls_to_targets = calls[calls['account_name'].isin(targets_list)].reset_index(drop=True)
calls_to_targets

call_name account_record_type parent_call       date  \
0    C004360772                 HCP         0.0 2020-01-16   
1    C004360774                 HCP         0.0 2020-01-16   
2    C004360775                 HCP         0.0 2020-01-16   
3    C004360778                 HCP         0.0 2020-01-16   
4    C004360779                 HCP         0.0 2020-01-16   
..          ...                 ...         ...        ...   
244  C010414398                 HCP         0.0 2021-09-14   
245  C010432790                 HCP         0.0 2021-09-14   
246  C010432734                 HCP         0.0 2021-09-14   
247  C010432747                 HCP         0.0 2021-09-14   
248  C010445545                 HCP         1.0 2021-09-17   

               datetime                 account_name  \
0   2020-01-16 21:17:00               Michael Sihver   
1   2020-01-16 21:17:00              Cecilia Nilsson   
2   2020-01-16 21:17:00              Zuzana Lovasová   
3   2020-01-16 21:17:00                  Paul Holmer   
4   2020-01-16 21:17:00  Helena Granstam Björneklett   
..                  ...                          ...   
244 2021-09-14 12:00:00                   Elin Jänes   
245 2021-09-14 12:00:00          Anna-Karin Wennstig   
246 2021-09-14 12:00:00                Petra Flygare   
247 2021-09-14 12:00:00                   Elin Jänes   
248 2021-09-17 09:00:00                 Sara Kinhult   

                                               address       address_line_1  \
0    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
1    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
2    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
3    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
4    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
..                                                 ...                  ...   
244  Lasarettsvägen 21, SUNDSVALL, Västernorrlands ...    Lasarettsvägen 21   
245  Lasarettsvägen 21, SUNDSVALL, Västernorrlands ...    Lasarettsvägen 21   
246  Lasarettsvägen 21, SUNDSVALL, Västernorrlands ...    Lasarettsvägen 21   
247  Lasarettsvägen 21, SUNDSVALL, Västernorrlands ...    Lasarettsvägen 21   
248                                                nan                  nan   

     attendees   attendee_type              call_focus       call_method  \
0          0.0  Person Account  Promotional discussion      Face to Face   
1          0.0  Person Account  Promotional discussion      Face to Face   
2          0.0  Person Account  Promotional discussion      Face to Face   
3          0.0  Person Account  Promotional discussion      Face to Face   
4          0.0  Person Account  Promotional discussion      Face to Face   
..         ...             ...                     ...               ...   
244        0.0  Person Account  Promotional discussion  Virtual MS Teams   
245        0.0  Person Account  Promotional discussion  Virtual MS Teams   
246        0.0  Person Account  Promotional discussion  Virtual MS Teams   
247        0.0  Person Account  Promotional discussion  Virtual MS Teams   
248        0.0  Person Account                     NaN  Virtual MS Teams   

     duration_in_minutes       account_id indication  
0                   30.0  0012o00002iEVSM   Melanoma  
1                   30.0  0012o00002iEZpE   Melanoma  
2                   30.0  0012o00002iEYvH   Melanoma  
3                   30.0  0012o00002kTA44   Melanoma  
4                   30.0  0012o00002iEeBl   Melanoma  
..                   ...              ...        ...  
244                 30.0  0012o00002iEVqj   Melanoma  
245                 60.0  0012o00002kTCww   Melanoma  
246                 60.0  0012o00002iEU5t   Melanoma  
247                 60.0  0012o00002iEVqj   Melanoma  
248                 60.0  0012o00002iEcCc   Melanoma  

[249 rows x 15 columns]

In [34]:
# take all calls at the moment, can later filter for 'promotional discussion' 
calls_to_targets = calls_to_targets[calls_to_targets['call_focus'] == 'Promotional discussion'].reset_index(drop=True)
# filter out all calls after 2021-08-31
calls_to_targets = calls_to_targets[calls_to_targets['date'] < "2021-09-01"]
calls_to_targets

call_name account_record_type parent_call       date  \
0    C004360772                 HCP         0.0 2020-01-16   
1    C004360774                 HCP         0.0 2020-01-16   
2    C004360775                 HCP         0.0 2020-01-16   
3    C004360778                 HCP         0.0 2020-01-16   
4    C004360779                 HCP         0.0 2020-01-16   
..          ...                 ...         ...        ...   
112  C010242106                 HCP         0.0 2021-08-27   
113  C010242107                 HCP         0.0 2021-08-27   
114  C010242108                 HCP         0.0 2021-08-27   
115  C010242038                 HCP         1.0 2021-08-27   
116  C010242111                 HCP         1.0 2021-08-27   

               datetime                 account_name  \
0   2020-01-16 21:17:00               Michael Sihver   
1   2020-01-16 21:17:00              Cecilia Nilsson   
2   2020-01-16 21:17:00              Zuzana Lovasová   
3   2020-01-16 21:17:00                  Paul Holmer   
4   2020-01-16 21:17:00  Helena Granstam Björneklett   
..                  ...                          ...   
112 2021-08-27 10:00:00                 Maria Ekholm   
113 2021-08-27 10:00:00           Christine Lundgren   
114 2021-08-27 10:00:00              Ida Spång Rosén   
115 2021-08-27 10:09:00               Henrik Lindman   
116 2021-08-27 10:16:00             Magnus Lagerlund   

                                               address       address_line_1  \
0    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
1    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
2    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
3    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
4    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...  Centrallasarettet 1   
..                                                 ...                  ...   
112  Sjukhusgatan, JÖNKÖPING, Jönköpings län F 5518...         Sjukhusgatan   
113  Sjukhusgatan, JÖNKÖPING, Jönköpings län F 5518...         Sjukhusgatan   
114  Sjukhusgatan, JÖNKÖPING, Jönköpings län F 5518...         Sjukhusgatan   
115  Sjukhusvägen 85, UPPSALA, Uppsala län C 75185 ...      Sjukhusvägen 85   
116  Lasarettsvägen 1, KALMAR, Kalmar län H 39244 S...     Lasarettsvägen 1   

     attendees   attendee_type              call_focus      call_method  \
0          0.0  Person Account  Promotional discussion     Face to Face   
1          0.0  Person Account  Promotional discussion     Face to Face   
2          0.0  Person Account  Promotional discussion     Face to Face   
3          0.0  Person Account  Promotional discussion     Face to Face   
4          0.0  Person Account  Promotional discussion     Face to Face   
..         ...             ...                     ...              ...   
112        0.0  Person Account  Promotional discussion    Virtual Other   
113        0.0  Person Account  Promotional discussion    Virtual Other   
114        0.0  Person Account  Promotional discussion    Virtual Other   
115        0.0  Person Account  Promotional discussion  Voice-only Call   
116        0.0  Person Account  Promotional discussion    Virtual Other   

     duration_in_minutes       account_id indication  
0                   30.0  0012o00002iEVSM   Melanoma  
1                   30.0  0012o00002iEZpE   Melanoma  
2                   30.0  0012o00002iEYvH   Melanoma  
3                   30.0  0012o00002kTA44   Melanoma  
4                   30.0  0012o00002iEeBl   Melanoma  
..                   ...              ...        ...  
112                 10.0  0012o00002iEezE         BC  
113                 10.0  0012o00002kT9YL         BC  
114                 10.0  0012o00002kTEOj         BC  
115                 30.0  0012o00002kTAh5         BC  
116                 10.0  0012o00002iESPQ         BC  

[117 rows x 15 columns]

In [35]:
calls_to_targets = calls_to_targets.filter(items=['date', 'account_name', 'address', 'call_focus', 'indication'])
calls_to_targets

date                 account_name  \
0   2020-01-16               Michael Sihver   
1   2020-01-16              Cecilia Nilsson   
2   2020-01-16              Zuzana Lovasová   
3   2020-01-16                  Paul Holmer   
4   2020-01-16  Helena Granstam Björneklett   
..         ...                          ...   
112 2021-08-27                 Maria Ekholm   
113 2021-08-27           Christine Lundgren   
114 2021-08-27              Ida Spång Rosén   
115 2021-08-27               Henrik Lindman   
116 2021-08-27             Magnus Lagerlund   

                                               address  \
0    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...   
1    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...   
2    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...   
3    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...   
4    Onkologikliniken, Centrallasarettet 1, VÄSTERÅ...   
..                                                 ...   
112  Sjukhusgatan, JÖNKÖPING, Jönköpings län F 5518...   
113  Sjukhusgatan, JÖNKÖPING, Jönköpings län F 5518...   
114  Sjukhusgatan, JÖNKÖPING, Jönköpings län F 5518...   
115  Sjukhusvägen 85, UPPSALA, Uppsala län C 75185 ...   
116  Lasarettsvägen 1, KALMAR, Kalmar län H 39244 S...   

                 call_focus indication  
0    Promotional discussion   Melanoma  
1    Promotional discussion   Melanoma  
2    Promotional discussion   Melanoma  
3    Promotional discussion   Melanoma  
4    Promotional discussion   Melanoma  
..                      ...        ...  
112  Promotional discussion         BC  
113  Promotional discussion         BC  
114  Promotional discussion         BC  
115  Promotional discussion         BC  
116  Promotional discussion         BC  

[117 rows x 5 columns]

In [36]:
# We already know the targets' addresses from targets_subsets
# create a dictionary from account_name and address
address_dict_targets = dict(zip(targets_subset.account_name, targets_subset.address))
address_dict_targets

{'Adel Bader Hamdalla': 'Brämhultsvägen 53, 501 82 Borås, Schweden',
 'Aglaia Schiza': 'Sjukhusvägen, 751 85 Uppsala, Schweden',
 'Agneta Nordin Danfors': 'Drottninggatan 68, 111 21 Stockholm, Schweden',
 'Ahmed Abbas Albu-Kareem': 'Universitetssjukhuset, 581 85 Linköping, Schweden',
 'Alaa Haidar': 'Lasarettsvägen, 302 33 Halmstad, Schweden',
 'Ana Bosch Campos': 'Lund, Schweden',
 'Andreas Nearchou': 'Kungsvägen 42, 633 49 Eskilstuna, Schweden',
 'Ulrika Bergqvist': 'Lasarettsvägen 29, 931 41 Skellefteå, Schweden',
 'Ann Charlotte Dreifaldt': 'Södra Grev Rosengatan, 701 85 Örebro, Schweden',
 'Elisabeth Ryd Ausén': 'Sankt Göransplan 1, 112 19 Stockholm, Schweden',
 'Marie Santonsson': 'Lasarettsvägen, 371 41 Karlskrona, Schweden',
 'Anna Nordenskjöld': 'Brämhultsvägen 53, 501 82 Borås, Schweden',
 'Anna von Wachenfeldt Väppling': 'Sjukhusbacken 10, 118 83 Stockholm, Schweden',
 'Anna-Karin Tzikas': 'Fjällvägen 9, 451 53 Uddevalla, Schweden',
 'Anna-Karin Wennstig': 'Lasarettsvägen 21

In [37]:
calls_to_targets['address'] = calls_to_targets['account_name'].apply(lambda x: address_dict_targets.get(x))
calls_to_targets

date                 account_name  \
0   2020-01-16               Michael Sihver   
1   2020-01-16              Cecilia Nilsson   
2   2020-01-16              Zuzana Lovasová   
3   2020-01-16                  Paul Holmer   
4   2020-01-16  Helena Granstam Björneklett   
..         ...                          ...   
112 2021-08-27                 Maria Ekholm   
113 2021-08-27           Christine Lundgren   
114 2021-08-27              Ida Spång Rosén   
115 2021-08-27               Henrik Lindman   
116 2021-08-27             Magnus Lagerlund   

                                       address              call_focus  \
0      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
1      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
2      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
3      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
4      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
..                                         ...                     ...   
112   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
113   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
114   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
115     Sjukhusvägen, 751 85 Uppsala, Schweden  Promotional discussion   
116  Lasarettsvägen 8, 392 44 Kalmar, Schweden  Promotional discussion   

    indication  
0     Melanoma  
1     Melanoma  
2     Melanoma  
3     Melanoma  
4     Melanoma  
..         ...  
112         BC  
113         BC  
114         BC  
115         BC  
116         BC  

[117 rows x 5 columns]

We create a new column `locality` that contains the city an HCP belongs to.

In [38]:
for i in range(len(calls_to_targets)):
    calls_to_targets.at[i, 'locality'] = calls_to_targets.at[i, 'address'].split(', ')[-2].split(' ')[-1]
    
calls_to_targets

date                 account_name  \
0   2020-01-16               Michael Sihver   
1   2020-01-16              Cecilia Nilsson   
2   2020-01-16              Zuzana Lovasová   
3   2020-01-16                  Paul Holmer   
4   2020-01-16  Helena Granstam Björneklett   
..         ...                          ...   
112 2021-08-27                 Maria Ekholm   
113 2021-08-27           Christine Lundgren   
114 2021-08-27              Ida Spång Rosén   
115 2021-08-27               Henrik Lindman   
116 2021-08-27             Magnus Lagerlund   

                                       address              call_focus  \
0      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
1      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
2      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
3      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
4      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
..                                         ...                     ...   
112   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
113   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
114   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
115     Sjukhusvägen, 751 85 Uppsala, Schweden  Promotional discussion   
116  Lasarettsvägen 8, 392 44 Kalmar, Schweden  Promotional discussion   

    indication   locality  
0     Melanoma   Västerås  
1     Melanoma   Västerås  
2     Melanoma   Västerås  
3     Melanoma   Västerås  
4     Melanoma   Västerås  
..         ...        ...  
112         BC  Jönköping  
113         BC  Jönköping  
114         BC  Jönköping  
115         BC    Uppsala  
116         BC     Kalmar  

[117 rows x 6 columns]

In order to add `municipality` - which unfortunately is not always identical to the brick - we merge `calls_to_targets` with `svenska_stader`.

In [39]:
# Merge with 'svenska_stader'
calls_to_targets = pd.merge(
    calls_to_targets, 
    svenska_stader, 
    on = 'locality',  
    how = 'left'
)
calls_to_targets

date                 account_name  \
0   2020-01-16               Michael Sihver   
1   2020-01-16              Cecilia Nilsson   
2   2020-01-16              Zuzana Lovasová   
3   2020-01-16                  Paul Holmer   
4   2020-01-16  Helena Granstam Björneklett   
..         ...                          ...   
112 2021-08-27                 Maria Ekholm   
113 2021-08-27           Christine Lundgren   
114 2021-08-27              Ida Spång Rosén   
115 2021-08-27               Henrik Lindman   
116 2021-08-27             Magnus Lagerlund   

                                       address              call_focus  \
0      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
1      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
2      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
3      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
4      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
..                                         ...                     ...   
112   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
113   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
114   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
115     Sjukhusvägen, 751 85 Uppsala, Schweden  Promotional discussion   
116  Lasarettsvägen 8, 392 44 Kalmar, Schweden  Promotional discussion   

    indication   locality municipality  
0     Melanoma   Västerås     Västerås  
1     Melanoma   Västerås     Västerås  
2     Melanoma   Västerås     Västerås  
3     Melanoma   Västerås     Västerås  
4     Melanoma   Västerås     Västerås  
..         ...        ...          ...  
112         BC  Jönköping    Jönköping  
113         BC  Jönköping    Jönköping  
114         BC  Jönköping    Jönköping  
115         BC    Uppsala      Uppsala  
116         BC     Kalmar       Kalmar  

[117 rows x 7 columns]

When looking at the values of `municipality` in `calls_to_targets` and comparing it to the values of `brick` in `mapping`, some things are striking:

* Solna (a suburb of Stockholm) has no mapped municipality
* It turns out that Solna is part of Solna Municipality 
* The city of Solna is part of the Stockholm urban area


* The locality of Visby is assigned to the municipality of Gotland but in mapping, Visby is a brick of its own. Therefore, change the municipality of Visby from Gotland to Visby.
* The locality of Göteborg is assigned to the municipality of Göteborg but in mapping, Göteborg is split into several bricks. Therefore, change the municipality of Göteborg from Göteborg to e.g. 'Göteborg-Centrum + V'.
* The locality of Kalmar is assigned to the municipality of Kalmar but in mapping, Kalmar appears as part of Kalmar/Nybro. Therefore, change the municipality of Kalmar from Kalmar to Kalmar/Nybro.
* The locality of Solna is not present in svenska_stader. As Solna is part of the Stockholm urban area, assign the locality Solna to e.g the municipality of 'Stockholm-NO'.
* The locality of Stockholm is assigned to the municipality of Stockholm but in mapping, Stockholm is split into several bricks. Therefore, change the municipality of Stockholm from Stockholm to e.g. 'Stockholm-NO'.
* The locality of Lidköping is assigned to the municipality of Lidköping but in mapping, Lidköping appears as part of Lidköping/Skara. Therefore, change the municipality of Lidköping from Lidköping to Lidköping/Skara.
* The locality of Helsingborg is assigned to the municipality of Helsingborg but in mapping, Helsingborg appears as part of Helsingborg/Landskrona. Therefore, change the municipality of Helsingborg from Helsingborg to Helsingborg/Landskrona.

In [40]:
for i in range(len(calls_to_targets)):
    if calls_to_targets.at[i, 'locality'] == 'Solna': #['municipality'] = 'Solna'
        calls_to_targets.at[i, 'municipality'] = 'Stockholm-NO' # instead of 'Solna'
calls_to_targets['municipality'] = calls_to_targets['municipality'].replace('Gotland', 'Visby')
calls_to_targets['municipality'] = calls_to_targets['municipality'].replace('Göteborg', 'Göteborg-Centrum + V')
calls_to_targets['municipality'] = calls_to_targets['municipality'].replace('Kalmar', 'Kalmar/Nybro')
calls_to_targets['municipality'] = calls_to_targets['municipality'].replace('Stockholm', 'Stockholm-NO')
calls_to_targets['municipality'] = calls_to_targets['municipality'].replace('Lidköping', 'Lidköping/Skara')
calls_to_targets['municipality'] = calls_to_targets['municipality'].replace('Helsingborg', 'Helsingborg/Landskrona')

calls_to_targets

date                 account_name  \
0   2020-01-16               Michael Sihver   
1   2020-01-16              Cecilia Nilsson   
2   2020-01-16              Zuzana Lovasová   
3   2020-01-16                  Paul Holmer   
4   2020-01-16  Helena Granstam Björneklett   
..         ...                          ...   
112 2021-08-27                 Maria Ekholm   
113 2021-08-27           Christine Lundgren   
114 2021-08-27              Ida Spång Rosén   
115 2021-08-27               Henrik Lindman   
116 2021-08-27             Magnus Lagerlund   

                                       address              call_focus  \
0      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
1      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
2      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
3      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
4      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
..                                         ...                     ...   
112   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
113   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
114   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
115     Sjukhusvägen, 751 85 Uppsala, Schweden  Promotional discussion   
116  Lasarettsvägen 8, 392 44 Kalmar, Schweden  Promotional discussion   

    indication   locality  municipality  
0     Melanoma   Västerås      Västerås  
1     Melanoma   Västerås      Västerås  
2     Melanoma   Västerås      Västerås  
3     Melanoma   Västerås      Västerås  
4     Melanoma   Västerås      Västerås  
..         ...        ...           ...  
112         BC  Jönköping     Jönköping  
113         BC  Jönköping     Jönköping  
114         BC  Jönköping     Jönköping  
115         BC    Uppsala       Uppsala  
116         BC     Kalmar  Kalmar/Nybro  

[117 rows x 7 columns]

In [41]:
calls_to_targets['date'] = calls_to_targets['date'].to_numpy().astype('datetime64[M]')
calls_to_targets

date                 account_name  \
0   2020-01-01               Michael Sihver   
1   2020-01-01              Cecilia Nilsson   
2   2020-01-01              Zuzana Lovasová   
3   2020-01-01                  Paul Holmer   
4   2020-01-01  Helena Granstam Björneklett   
..         ...                          ...   
112 2021-08-01                 Maria Ekholm   
113 2021-08-01           Christine Lundgren   
114 2021-08-01              Ida Spång Rosén   
115 2021-08-01               Henrik Lindman   
116 2021-08-01             Magnus Lagerlund   

                                       address              call_focus  \
0      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
1      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
2      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
3      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
4      Sigtunagatan, 721 89 Västerås, Schweden  Promotional discussion   
..                                         ...                     ...   
112   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
113   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
114   Sjukhusgatan, 553 05 Jönköping, Schweden  Promotional discussion   
115     Sjukhusvägen, 751 85 Uppsala, Schweden  Promotional discussion   
116  Lasarettsvägen 8, 392 44 Kalmar, Schweden  Promotional discussion   

    indication   locality  municipality  
0     Melanoma   Västerås      Västerås  
1     Melanoma   Västerås      Västerås  
2     Melanoma   Västerås      Västerås  
3     Melanoma   Västerås      Västerås  
4     Melanoma   Västerås      Västerås  
..         ...        ...           ...  
112         BC  Jönköping     Jönköping  
113         BC  Jönköping     Jönköping  
114         BC  Jönköping     Jönköping  
115         BC    Uppsala       Uppsala  
116         BC     Kalmar  Kalmar/Nybro  

[117 rows x 7 columns]

In [42]:
calls_to_targets['date'].unique()

array(['2020-01-01T00:00:00.000000000', '2020-02-01T00:00:00.000000000',
       '2020-03-01T00:00:00.000000000', '2020-05-01T00:00:00.000000000',
       '2020-09-01T00:00:00.000000000', '2020-10-01T00:00:00.000000000',
       '2020-11-01T00:00:00.000000000', '2021-02-01T00:00:00.000000000',
       '2021-03-01T00:00:00.000000000', '2021-04-01T00:00:00.000000000',
       '2021-05-01T00:00:00.000000000', '2021-06-01T00:00:00.000000000',
       '2021-08-01T00:00:00.000000000'], dtype='datetime64[ns]')

In order to be able to merge `mapping` to `calls_to_targets`, we need to ensure that the `brick` variable in `mapping` and the `municipality` variable in `calls_to_targets` have the same format, i.e., the two digits at the start of any entry in `brick` must be removed.

In [43]:
mapping['brick'] = mapping['brick'].astype(str)
for i in range(len(mapping)):
    brick_split_list = mapping['brick'][i].split(' ')[1:]
    mapping.at[i, 'brick'] = ' '.join(brick_split_list)
mapping

brick                 sweden_bc                      sweden_me
0        Norrtälje                 Stockholm                 Stockholm ONCO
1          Uppsala                   Uppsala                   Uppsala ONCO
2         Enköping                   Uppsala                   Uppsala ONCO
3         Nyköping       Sörmland-Eskilstuna       Sörmland-Eskilstuna ONCO
4      Katrineholm       Sörmland-Eskilstuna       Sörmland-Eskilstuna ONCO
..             ...                       ...                            ...
73         Kungälv  Västra Götaland-Göteborg  Västra Götaland-Göteborg ONCO
74  Lerum/Alingsås  Västra Götaland-Alingsås       Västra Götaland-SÄS ONCO
75           Malmö                Skåne-Lund                     Skåne ONCO
76            Lund                Skåne-Lund                     Skåne ONCO
77      Trelleborg                Skåne-Lund                     Skåne ONCO

[78 rows x 3 columns]

In [44]:
# create mappings table for all dates
counts = mapping.copy()
counts_by_date = pd.DataFrame()
for date in calls_to_targets['date'].unique():
    counts_ex = counts.copy()
    counts_ex['date'] = date
    counts_by_date = pd.concat([counts_by_date, counts_ex], ignore_index=True)
counts_by_date

brick                 sweden_bc                      sweden_me  \
0          Norrtälje                 Stockholm                 Stockholm ONCO   
1            Uppsala                   Uppsala                   Uppsala ONCO   
2           Enköping                   Uppsala                   Uppsala ONCO   
3           Nyköping       Sörmland-Eskilstuna       Sörmland-Eskilstuna ONCO   
4        Katrineholm       Sörmland-Eskilstuna       Sörmland-Eskilstuna ONCO   
...              ...                       ...                            ...   
1009         Kungälv  Västra Götaland-Göteborg  Västra Götaland-Göteborg ONCO   
1010  Lerum/Alingsås  Västra Götaland-Alingsås       Västra Götaland-SÄS ONCO   
1011           Malmö                Skåne-Lund                     Skåne ONCO   
1012            Lund                Skåne-Lund                     Skåne ONCO   
1013      Trelleborg                Skåne-Lund                     Skåne ONCO   

           date  
0    2020-01-01  
1    2020-01-01  
2    2020-01-01  
3    2020-01-01  
4    2020-01-01  
...         ...  
1009 2021-08-01  
1010 2021-08-01  
1011 2021-08-01  
1012 2021-08-01  
1013 2021-08-01  

[1014 rows x 4 columns]

We can now create the call counts for the BC and Melanoma regions using the function `aggregate_by_regions_and_dates()`.

In [45]:
calls_counts = aggregate_by_regions_and_dates(counts_by_date, calls_to_targets, 'address', 'calls')
calls_counts

date                      territory  calls
0   2020-01-01                       Blekinge    0.0
1   2020-01-01                        Dalarna    0.0
2   2020-01-01                Gävleborg-Gävle    0.0
3   2020-01-01               Halland-Halmstad    0.0
4   2020-01-01     Halland-Varberg-Falkenberg    0.0
..         ...                            ...    ...
736 2021-08-01      Västmanland-Västerås ONCO    0.0
737 2021-08-01  Västra Götaland-Göteborg ONCO    1.0
738 2021-08-01       Västra Götaland-SÄS ONCO    0.0
739 2021-08-01             Örebro-Örebro ONCO    0.0
740 2021-08-01    Östergötland-Linköping ONCO    0.0

[741 rows x 3 columns]

In [46]:
calls_counts['calls'].sum()

117.0

In [60]:
# Save the new dataset
    
if not os.path.exists(route0):
    os.mkdir(route0)

print("saving file corresponding to call_counts.pkl")
calls_counts.to_pickle(f"{route0}/call_counts.pkl")
pd.read_pickle(f"{route0}/call_counts.pkl")

saving file corresponding to call_counts.pkl


date                      territory  calls
0   2020-01-01                       Blekinge    0.0
1   2020-01-01                        Dalarna    0.0
2   2020-01-01                Gävleborg-Gävle    0.0
3   2020-01-01               Halland-Halmstad    0.0
4   2020-01-01     Halland-Varberg-Falkenberg    0.0
..         ...                            ...    ...
736 2021-08-01      Västmanland-Västerås ONCO    0.0
737 2021-08-01  Västra Götaland-Göteborg ONCO    1.0
738 2021-08-01       Västra Götaland-SÄS ONCO    0.0
739 2021-08-01             Örebro-Örebro ONCO    0.0
740 2021-08-01    Östergötland-Linköping ONCO    0.0

[741 rows x 3 columns]

## 4. HCP, hospital and calls counts per BC and Melanoma region

In [47]:
targets_subset

account_name                 top_account_name indication  \
0        Adel Bader Hamdalla    Södra Älvsborgs Sjukhus Borås         BC   
1              Aglaia Schiza             Akademiska sjukhuset         BC   
2      Agneta Nordin Danfors            Drottningmottagningen         BC   
3    Ahmed Abbas Albu-Kareem  Universitetssjukhuset Linköping         BC   
4                Alaa Haidar        Hallands sjukhus Halmstad         BC   
..                       ...                              ...        ...   
224   Ylva Holmgren Stenlund    Norrlands Universitetssjukhus   Melanoma   
225              Anna Nyberg              Länssjukhuset Ryhov         BC   
226          Göran Carlstedt          Centrallasarettet Växjö   Melanoma   
227         Mikael Wallander              Länssjukhuset Ryhov   Melanoma   
228          Frida Jakobsson     Universitetssjukhuset Örebro   Melanoma   

                                               address  
0            Brämhultsvägen 53, 501 82 Borås, Schweden  
1               Sjukhusvägen, 751 85 Uppsala, Schweden  
2        Drottninggatan 68, 111 21 Stockholm, Schweden  
3    Universitetssjukhuset, 581 85 Linköping, Schweden  
4            Lasarettsvägen, 302 33 Halmstad, Schweden  
..                                                 ...  
224          Daniel Naezéns väg, 907 37 Umeå, Schweden  
225           Sjukhusgatan, 553 05 Jönköping, Schweden  
226              Strandvägen 8, 352 34 Växjö, Schweden  
227           Sjukhusgatan, 553 05 Jönköping, Schweden  
228     Södra Grev Rosengatan, 701 85 Örebro, Schweden  

[229 rows x 4 columns]

We create a new column `locality` that contains the city an HCP belongs to.

In [48]:
# For now, only continue with 'targets_subset'
for i in range(len(targets_subset)):
    targets_subset.at[i, 'locality'] = targets_subset.at[i, 'address'].split(', ')[-2].split(' ')[-1]
    
targets_subset

account_name                 top_account_name indication  \
0        Adel Bader Hamdalla    Södra Älvsborgs Sjukhus Borås         BC   
1              Aglaia Schiza             Akademiska sjukhuset         BC   
2      Agneta Nordin Danfors            Drottningmottagningen         BC   
3    Ahmed Abbas Albu-Kareem  Universitetssjukhuset Linköping         BC   
4                Alaa Haidar        Hallands sjukhus Halmstad         BC   
..                       ...                              ...        ...   
224   Ylva Holmgren Stenlund    Norrlands Universitetssjukhus   Melanoma   
225              Anna Nyberg              Länssjukhuset Ryhov         BC   
226          Göran Carlstedt          Centrallasarettet Växjö   Melanoma   
227         Mikael Wallander              Länssjukhuset Ryhov   Melanoma   
228          Frida Jakobsson     Universitetssjukhuset Örebro   Melanoma   

                                               address   locality  
0            Brämhultsvägen 53, 501 82 Borås, Schweden      Borås  
1               Sjukhusvägen, 751 85 Uppsala, Schweden    Uppsala  
2        Drottninggatan 68, 111 21 Stockholm, Schweden  Stockholm  
3    Universitetssjukhuset, 581 85 Linköping, Schweden  Linköping  
4            Lasarettsvägen, 302 33 Halmstad, Schweden   Halmstad  
..                                                 ...        ...  
224          Daniel Naezéns väg, 907 37 Umeå, Schweden       Umeå  
225           Sjukhusgatan, 553 05 Jönköping, Schweden  Jönköping  
226              Strandvägen 8, 352 34 Växjö, Schweden      Växjö  
227           Sjukhusgatan, 553 05 Jönköping, Schweden  Jönköping  
228     Södra Grev Rosengatan, 701 85 Örebro, Schweden     Örebro  

[229 rows x 5 columns]

In order to get the corresponding municipality - which unfortunately is not always identical to the brick - we merge `targets_subset` with `svenska_stader`.

In [49]:
# Merge with 'svenska_stader'
targets_subset = pd.merge(
    targets_subset, 
    svenska_stader, 
    on = 'locality',  
    how = 'left'
)
targets_subset

account_name                 top_account_name indication  \
0        Adel Bader Hamdalla    Södra Älvsborgs Sjukhus Borås         BC   
1              Aglaia Schiza             Akademiska sjukhuset         BC   
2      Agneta Nordin Danfors            Drottningmottagningen         BC   
3    Ahmed Abbas Albu-Kareem  Universitetssjukhuset Linköping         BC   
4                Alaa Haidar        Hallands sjukhus Halmstad         BC   
..                       ...                              ...        ...   
224   Ylva Holmgren Stenlund    Norrlands Universitetssjukhus   Melanoma   
225              Anna Nyberg              Länssjukhuset Ryhov         BC   
226          Göran Carlstedt          Centrallasarettet Växjö   Melanoma   
227         Mikael Wallander              Länssjukhuset Ryhov   Melanoma   
228          Frida Jakobsson     Universitetssjukhuset Örebro   Melanoma   

                                               address   locality municipality  
0            Brämhultsvägen 53, 501 82 Borås, Schweden      Borås        Borås  
1               Sjukhusvägen, 751 85 Uppsala, Schweden    Uppsala      Uppsala  
2        Drottninggatan 68, 111 21 Stockholm, Schweden  Stockholm    Stockholm  
3    Universitetssjukhuset, 581 85 Linköping, Schweden  Linköping    Linköping  
4            Lasarettsvägen, 302 33 Halmstad, Schweden   Halmstad     Halmstad  
..                                                 ...        ...          ...  
224          Daniel Naezéns väg, 907 37 Umeå, Schweden       Umeå         Umeå  
225           Sjukhusgatan, 553 05 Jönköping, Schweden  Jönköping    Jönköping  
226              Strandvägen 8, 352 34 Växjö, Schweden      Växjö        Växjö  
227           Sjukhusgatan, 553 05 Jönköping, Schweden  Jönköping    Jönköping  
228     Södra Grev Rosengatan, 701 85 Örebro, Schweden     Örebro       Örebro  

[229 rows x 6 columns]

When looking at the values of `municipality` in `targets_subset` and comparing it to the values of `brick` in `mapping`, some things are striking:

* Solna (a suburb of Stockholm) has no mapped municipality
* It turns out that Solna is part of Solna Municipality 
* The city of Solna is part of the Stockholm urban area


* The locality of Visby is assigned to the municipality of Gotland but in mapping, Visby is a brick of its own. Therefore, change the municipality of Visby from Gotland to Visby.
* The locality of Göteborg is assigned to the municipality of Göteborg but in mapping, Göteborg is split into several bricks. Therefore, change the municipality of Göteborg from Göteborg to e.g. 'Göteborg-Centrum + V'.
* The locality of Kalmar is assigned to the municipality of Kalmar but in mapping, Kalmar appears as part of Kalmar/Nybro. Therefore, change the municipality of Kalmar from Kalmar to Kalmar/Nybro.
* The locality of Solna is not present in svenska_stader. As Solna is part of the Stockholm urban area, assign the locality Solna to e.g the municipality of 'Stockholm-NO'.
* The locality of Stockholm is assigned to the municipality of Stockholm but in mapping, Stockholm is split into several bricks. Therefore, change the municipality of Stockholm from Stockholm to e.g. 'Stockholm-NO'.
* The locality of Lidköping is assigned to the municipality of Lidköping but in mapping, Lidköping appears as part of Lidköping/Skara. Therefore, change the municipality of Lidköping from Lidköping to Lidköping/Skara.
* The locality of Helsingborg is assigned to the municipality of Helsingborg but in mapping, Helsingborg appears as part of Helsingborg/Landskrona. Therefore, change the municipality of Helsingborg from Helsingborg to Helsingborg/Landskrona.

In [50]:
for i in range(len(targets_subset)):
    if targets_subset.at[i, 'locality'] == 'Solna': #['municipality'] = 'Solna'
        targets_subset.at[i, 'municipality'] = 'Stockholm-NO' # instead of 'Solna'
targets_subset['municipality'] = targets_subset['municipality'].replace('Gotland', 'Visby')
targets_subset['municipality'] = targets_subset['municipality'].replace('Göteborg', 'Göteborg-Centrum + V')
targets_subset['municipality'] = targets_subset['municipality'].replace('Kalmar', 'Kalmar/Nybro')
targets_subset['municipality'] = targets_subset['municipality'].replace('Stockholm', 'Stockholm-NO')
targets_subset['municipality'] = targets_subset['municipality'].replace('Lidköping', 'Lidköping/Skara')
targets_subset['municipality'] = targets_subset['municipality'].replace('Helsingborg', 'Helsingborg/Landskrona')

targets_subset

account_name                 top_account_name indication  \
0        Adel Bader Hamdalla    Södra Älvsborgs Sjukhus Borås         BC   
1              Aglaia Schiza             Akademiska sjukhuset         BC   
2      Agneta Nordin Danfors            Drottningmottagningen         BC   
3    Ahmed Abbas Albu-Kareem  Universitetssjukhuset Linköping         BC   
4                Alaa Haidar        Hallands sjukhus Halmstad         BC   
..                       ...                              ...        ...   
224   Ylva Holmgren Stenlund    Norrlands Universitetssjukhus   Melanoma   
225              Anna Nyberg              Länssjukhuset Ryhov         BC   
226          Göran Carlstedt          Centrallasarettet Växjö   Melanoma   
227         Mikael Wallander              Länssjukhuset Ryhov   Melanoma   
228          Frida Jakobsson     Universitetssjukhuset Örebro   Melanoma   

                                               address   locality  \
0            Brämhultsvägen 53, 501 82 Borås, Schweden      Borås   
1               Sjukhusvägen, 751 85 Uppsala, Schweden    Uppsala   
2        Drottninggatan 68, 111 21 Stockholm, Schweden  Stockholm   
3    Universitetssjukhuset, 581 85 Linköping, Schweden  Linköping   
4            Lasarettsvägen, 302 33 Halmstad, Schweden   Halmstad   
..                                                 ...        ...   
224          Daniel Naezéns väg, 907 37 Umeå, Schweden       Umeå   
225           Sjukhusgatan, 553 05 Jönköping, Schweden  Jönköping   
226              Strandvägen 8, 352 34 Växjö, Schweden      Växjö   
227           Sjukhusgatan, 553 05 Jönköping, Schweden  Jönköping   
228     Södra Grev Rosengatan, 701 85 Örebro, Schweden     Örebro   

     municipality  
0           Borås  
1         Uppsala  
2    Stockholm-NO  
3       Linköping  
4        Halmstad  
..            ...  
224          Umeå  
225     Jönköping  
226         Växjö  
227     Jönköping  
228        Örebro  

[229 rows x 6 columns]

The table `mapping` is already in the correct format, i.e., the `brick` variable in `mapping` and the `municipality` variable in `targets_subset` have the same format, i.e., the two digits at the start of any entry in `brick` must be removed.

We can now create the hospital and HCP counts for the BC and Melanoma regions using the function `aggregate_by_regions()`.

In [51]:
hospital_counts = aggregate_by_regions(mapping, targets_subset, 'address', 'hospitals')
hospital_counts

territory  hospitals
0                        Blekinge        1.0
1                         Dalarna        0.0
2                 Gävleborg-Gävle        0.0
3                Halland-Halmstad        1.0
4      Halland-Varberg-Falkenberg        0.0
5                        Jämtland        1.0
6             Jönköping-Jönköping        1.0
7          Jönköping-Nässjö-Eksjö        0.0
8               Jönköping-Värnamo        0.0
9                          Kalmar        1.0
10              Kronoberg-Ljungby        0.0
11                Kronoberg-Växjö        1.0
12           Norrbotten-Sunderbyn        0.0
13                       SE-other        0.0
14   Skåne-Helsingborg-Landskrona        1.0
15             Skåne-Kristianstad        0.0
16                     Skåne-Lund        3.0
17                      Stockholm        5.0
18              Stockholm-Gotland        1.0
19            Sörmland-Eskilstuna        1.0
20                        Uppsala        2.0
21              Värmland-Karlstad        1.0
22        Västerbotten-Skellefteå        1.0
23              Västerbotten-Umeå        1.0
24       Västernorrland-Sundsvall        1.0
25    Västernorrland-Örnsköldsvik        0.0
26           Västmanland-Västerås        1.0
27       Västra Götaland-Alingsås        0.0
28          Västra Götaland-Borås        1.0
29       Västra Götaland-Göteborg        1.0
30      Västra Götaland-Lidköping        1.0
31         Västra Götaland-Skövde        1.0
32      Västra Götaland-Uddevalla        1.0
33                  Örebro-Örebro        1.0
34         Östergötland-Linköping        1.0
35        Östergötland-Norrköping        0.0
36                  Blekinge ONCO        0.0
37                   Dalarna ONCO        0.0
38           Gävleborg-Gävle ONCO        1.0
39          Halland-Halmstad ONCO        0.0
40                  Jämtland ONCO        1.0
41                 Jönköping ONCO        1.0
42                    Kalmar ONCO        1.0
43           Kronoberg-Växjö ONCO        1.0
44      Norrbotten-Sunderbyn ONCO        0.0
45                  SE-other ONCO        0.0
46                     Skåne ONCO        1.0
47                 Stockholm ONCO        1.0
48         Stockholm-Gotland ONCO        1.0
49       Sörmland-Eskilstuna ONCO        1.0
50                   Uppsala ONCO        1.0
51         Värmland-Karlstad ONCO        1.0
52         Västerbotten-Umeå ONCO        1.0
53  Västernorrland-Sundsvall ONCO        1.0
54      Västmanland-Västerås ONCO        1.0
55  Västra Götaland-Göteborg ONCO        1.0
56       Västra Götaland-SÄS ONCO        1.0
57             Örebro-Örebro ONCO        1.0
58    Östergötland-Linköping ONCO        1.0

In [53]:
hcp_counts = aggregate_by_regions(mapping, targets_subset, 'account_name', 'hcps')
hcp_counts

territory  hcps
0                        Blekinge   5.0
1                         Dalarna   0.0
2                 Gävleborg-Gävle   0.0
3                Halland-Halmstad   1.0
4      Halland-Varberg-Falkenberg   0.0
5                        Jämtland   2.0
6             Jönköping-Jönköping   6.0
7          Jönköping-Nässjö-Eksjö   0.0
8               Jönköping-Värnamo   0.0
9                          Kalmar   7.0
10              Kronoberg-Ljungby   0.0
11                Kronoberg-Växjö   5.0
12           Norrbotten-Sunderbyn   0.0
13                       SE-other   0.0
14   Skåne-Helsingborg-Landskrona   1.0
15             Skåne-Kristianstad   0.0
16                     Skåne-Lund  16.0
17                      Stockholm  41.0
18              Stockholm-Gotland   2.0
19            Sörmland-Eskilstuna   3.0
20                        Uppsala  10.0
21              Värmland-Karlstad   2.0
22        Västerbotten-Skellefteå   2.0
23              Västerbotten-Umeå  10.0
24       Västernorrland-Sundsvall   4.0
25    Västernorrland-Örnsköldsvik   0.0
26           Västmanland-Västerås   3.0
27       Västra Götaland-Alingsås   0.0
28          Västra Götaland-Borås   4.0
29       Västra Götaland-Göteborg   8.0
30      Västra Götaland-Lidköping   2.0
31         Västra Götaland-Skövde   1.0
32      Västra Götaland-Uddevalla   3.0
33                  Örebro-Örebro   3.0
34         Östergötland-Linköping   3.0
35        Östergötland-Norrköping   0.0
36                  Blekinge ONCO   0.0
37                   Dalarna ONCO   0.0
38           Gävleborg-Gävle ONCO   3.0
39          Halland-Halmstad ONCO   0.0
40                  Jämtland ONCO   2.0
41                 Jönköping ONCO   4.0
42                    Kalmar ONCO   4.0
43           Kronoberg-Växjö ONCO   1.0
44      Norrbotten-Sunderbyn ONCO   0.0
45                  SE-other ONCO   0.0
46                     Skåne ONCO   5.0
47                 Stockholm ONCO  10.0
48         Stockholm-Gotland ONCO   2.0
49       Sörmland-Eskilstuna ONCO   4.0
50                   Uppsala ONCO   7.0
51         Värmland-Karlstad ONCO   6.0
52         Västerbotten-Umeå ONCO  10.0
53  Västernorrland-Sundsvall ONCO   2.0
54      Västmanland-Västerås ONCO   5.0
55  Västra Götaland-Göteborg ONCO   7.0
56       Västra Götaland-SÄS ONCO   1.0
57             Örebro-Örebro ONCO   5.0
58    Östergötland-Linköping ONCO   2.0

In [68]:
# Save the new dataset

if not os.path.exists(route0):
    os.mkdir(route0)
    
print("saving file corresponding to hospital_counts.pkl")
hospital_counts.to_pickle(f"{route0}/hospital_counts.pkl")
pd.read_pickle(f"{route0}/hospital_counts.pkl")

saving file corresponding to hospital_counts.pkl


territory  hospitals
0                        Blekinge        1.0
1                         Dalarna        0.0
2                 Gävleborg-Gävle        0.0
3                Halland-Halmstad        1.0
4      Halland-Varberg-Falkenberg        0.0
5                        Jämtland        1.0
6             Jönköping-Jönköping        1.0
7          Jönköping-Nässjö-Eksjö        0.0
8               Jönköping-Värnamo        0.0
9                          Kalmar        1.0
10              Kronoberg-Ljungby        0.0
11                Kronoberg-Växjö        1.0
12           Norrbotten-Sunderbyn        0.0
13                       SE-other        0.0
14   Skåne-Helsingborg-Landskrona        1.0
15             Skåne-Kristianstad        0.0
16                     Skåne-Lund        3.0
17                      Stockholm        5.0
18              Stockholm-Gotland        1.0
19            Sörmland-Eskilstuna        1.0
20                        Uppsala        2.0
21              Värmland-Karlstad        1.0
22        Västerbotten-Skellefteå        1.0
23              Västerbotten-Umeå        1.0
24       Västernorrland-Sundsvall        1.0
25    Västernorrland-Örnsköldsvik        0.0
26           Västmanland-Västerås        1.0
27       Västra Götaland-Alingsås        0.0
28          Västra Götaland-Borås        1.0
29       Västra Götaland-Göteborg        1.0
30      Västra Götaland-Lidköping        1.0
31         Västra Götaland-Skövde        1.0
32      Västra Götaland-Uddevalla        1.0
33                  Örebro-Örebro        1.0
34         Östergötland-Linköping        1.0
35        Östergötland-Norrköping        0.0
36                  Blekinge ONCO        0.0
37                   Dalarna ONCO        0.0
38           Gävleborg-Gävle ONCO        1.0
39          Halland-Halmstad ONCO        0.0
40                  Jämtland ONCO        1.0
41                 Jönköping ONCO        1.0
42                    Kalmar ONCO        1.0
43           Kronoberg-Växjö ONCO        1.0
44      Norrbotten-Sunderbyn ONCO        0.0
45                  SE-other ONCO        0.0
46                     Skåne ONCO        1.0
47                 Stockholm ONCO        1.0
48         Stockholm-Gotland ONCO        1.0
49       Sörmland-Eskilstuna ONCO        1.0
50                   Uppsala ONCO        1.0
51         Värmland-Karlstad ONCO        1.0
52         Västerbotten-Umeå ONCO        1.0
53  Västernorrland-Sundsvall ONCO        1.0
54      Västmanland-Västerås ONCO        1.0
55  Västra Götaland-Göteborg ONCO        1.0
56       Västra Götaland-SÄS ONCO        1.0
57             Örebro-Örebro ONCO        1.0
58    Östergötland-Linköping ONCO        1.0

In [54]:
# Save the new dataset
    
if not os.path.exists(route0):
    os.mkdir(route0)

print("saving file corresponding to hcp_counts.pkl")
hcp_counts.to_pickle(f"{route0}/hcp_counts.pkl")
pd.read_pickle(f"{route0}/hcp_counts.pkl")

saving file corresponding to hcp_counts.pkl


territory  hcps
0                        Blekinge   5.0
1                         Dalarna   0.0
2                 Gävleborg-Gävle   0.0
3                Halland-Halmstad   1.0
4      Halland-Varberg-Falkenberg   0.0
5                        Jämtland   2.0
6             Jönköping-Jönköping   6.0
7          Jönköping-Nässjö-Eksjö   0.0
8               Jönköping-Värnamo   0.0
9                          Kalmar   7.0
10              Kronoberg-Ljungby   0.0
11                Kronoberg-Växjö   5.0
12           Norrbotten-Sunderbyn   0.0
13                       SE-other   0.0
14   Skåne-Helsingborg-Landskrona   1.0
15             Skåne-Kristianstad   0.0
16                     Skåne-Lund  16.0
17                      Stockholm  41.0
18              Stockholm-Gotland   2.0
19            Sörmland-Eskilstuna   3.0
20                        Uppsala  10.0
21              Värmland-Karlstad   2.0
22        Västerbotten-Skellefteå   2.0
23              Västerbotten-Umeå  10.0
24       Västernorrland-Sundsvall   4.0
25    Västernorrland-Örnsköldsvik   0.0
26           Västmanland-Västerås   3.0
27       Västra Götaland-Alingsås   0.0
28          Västra Götaland-Borås   4.0
29       Västra Götaland-Göteborg   8.0
30      Västra Götaland-Lidköping   2.0
31         Västra Götaland-Skövde   1.0
32      Västra Götaland-Uddevalla   3.0
33                  Örebro-Örebro   3.0
34         Östergötland-Linköping   3.0
35        Östergötland-Norrköping   0.0
36                  Blekinge ONCO   0.0
37                   Dalarna ONCO   0.0
38           Gävleborg-Gävle ONCO   3.0
39          Halland-Halmstad ONCO   0.0
40                  Jämtland ONCO   2.0
41                 Jönköping ONCO   4.0
42                    Kalmar ONCO   4.0
43           Kronoberg-Växjö ONCO   1.0
44      Norrbotten-Sunderbyn ONCO   0.0
45                  SE-other ONCO   0.0
46                     Skåne ONCO   5.0
47                 Stockholm ONCO  10.0
48         Stockholm-Gotland ONCO   2.0
49       Sörmland-Eskilstuna ONCO   4.0
50                   Uppsala ONCO   7.0
51         Värmland-Karlstad ONCO   6.0
52         Västerbotten-Umeå ONCO  10.0
53  Västernorrland-Sundsvall ONCO   2.0
54      Västmanland-Västerås ONCO   5.0
55  Västra Götaland-Göteborg ONCO   7.0
56       Västra Götaland-SÄS ONCO   1.0
57             Örebro-Örebro ONCO   5.0
58    Östergötland-Linköping ONCO   2.0